package com.huarenzaimeng.api.payment;

import com.huarenzaimeng.api.BusinessEventStore;
import com.huarenzaimeng.core.BusinessEventLinker;
import org.junit.jupiter.api.Test;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;
import static org.assertj.core.api.Assertions.*;

class WeChatPayCoordinatorTest {
 private static final String D="a".repeat(64);private static final PaymentOrderSnapshotPort.Snapshot S=new PaymentOrderSnapshotPort.Snapshot("ORDER-1","BUYER-1","QUOTE-1","b".repeat(64),1000,"CNY");private static final WeChatPayCoordinator.NotificationAuthority AUTH=new WeChatPayCoordinator.NotificationAuthority("APP","MCH",Set.of("CERT"));
 @Test void createUsesTrustedSnapshotAndReplayBindsEveryField(){MemoryStore s=new MemoryStore();Port p=new Port(new WeChatPayPort.Unknown("OFF"));Events e=new Events();WeChatPayCoordinator c=new WeChatPayCoordinator(p,s,o->S,2,AUTH,e);assertThat(c.create(new WeChatPayCoordinator.CreateCommand("ORDER-1",D)).amountMinor()).isEqualTo(1000);c.create(new WeChatPayCoordinator.CreateCommand("ORDER-1",D));assertThat(p.calls).hasValue(1);assertThat(p.last.payerSubjectRef()).isEqualTo("BUYER-1");assertThat(e.types).as("coordinator must not publish after store commit").isEmpty();s.row.s=new PaymentOrderSnapshotPort.Snapshot("ORDER-1","OTHER","QUOTE-1","b".repeat(64),1000,"CNY");assertThatThrownBy(()->c.create(new WeChatPayCoordinator.CreateCommand("ORDER-1",D))).hasMessage("PAYMENT_IDEMPOTENCY_CONFLICT");}
 @Test void notificationRequiresConfiguredExactAuthorityAndIsDigestIdempotent(){MemoryStore s=new MemoryStore();Port p=new Port(new WeChatPayPort.Accepted("WX","PREPAY_CREATED","EV"));Events e=new Events();WeChatPayCoordinator c=new WeChatPayCoordinator(p,s,o->S,2,AUTH,e);c.create(new WeChatPayCoordinator.CreateCommand("ORDER-1",D));p.notice=notice("N1","c".repeat(64),1000,"PAID","APP","MCH","CERT");assertThat(c.notification(env("N1")).state()).isEqualTo(WeChatPayCoordinator.State.PAID);assertThat(e.types).as("coordinator must not publish after store commit").isEmpty();c.notification(env("N1"));p.notice=notice("N1","d".repeat(64),1000,"PAID","APP","MCH","CERT");assertThatThrownBy(()->c.notification(env("N1"))).hasMessage("PAYMENT_NOTIFICATION_ID_CONFLICT");p.notice=notice("N2","e".repeat(64),1000,"PAID","OTHER","MCH","CERT");assertThatThrownBy(()->c.notification(env("N2"))).hasMessage("PAYMENT_NOTIFICATION_AUTHORITY_CONFLICT");WeChatPayCoordinator unconfigured=new WeChatPayCoordinator(p,new MemoryStore(),o->S,2,new WeChatPayCoordinator.NotificationAuthority("","",Set.of()),new Events());unconfigured.create(new WeChatPayCoordinator.CreateCommand("ORDER-1",D));assertThatThrownBy(()->unconfigured.notification(env("N2"))).hasMessage("PAYMENT_NOTIFICATION_AUTHORITY_NOT_CONFIGURED");}
 @Test void rejectedRefundReleasesCumulativeAndUnknownIsQueryableWithoutDuplicateApply(){MemoryStore s=new MemoryStore();Port p=new Port(new WeChatPayPort.Accepted("WX","PREPAY_CREATED","EV"));WeChatPayCoordinator c=new WeChatPayCoordinator(p,s,o->S,1,AUTH,new Events());c.create(new WeChatPayCoordinator.CreateCommand("ORDER-1",D));s.row.state=WeChatPayCoordinator.State.PAID;p.result=new WeChatPayPort.Rejected("NO");c.refund(new WeChatPayPort.Refund("ORDER-1","R1",600,"f".repeat(64)));assertThat(s.row.refunded).isZero();assertThat(s.row.state).isEqualTo(WeChatPayCoordinator.State.PAID);p.result=new WeChatPayPort.Unknown("TIMEOUT");c.refund(new WeChatPayPort.Refund("ORDER-1","R2",500,"1".repeat(64)));assertThat(c.refundStatus("R2").state()).isEqualTo(WeChatPayCoordinator.RefundState.UNKNOWN);c.refund(new WeChatPayPort.Refund("ORDER-1","R2",500,"1".repeat(64)));assertThat(s.row.refunded).isEqualTo(500);}
 @Test void unknownRefundQueryConvergesToSuccessAndKeepsReservedAmountEvenWhenPaymentWindowExpired(){Harness h=unknownRefund();h.store.row.deadline=Instant.EPOCH;h.port.refundQuery=new WeChatPayPort.RefundObservation("R1","ORDER-1",500,"CNY","SUCCEEDED","QUERY-EV");assertThat(h.coordinator.queryRefundOriginal("R1").state()).isEqualTo(WeChatPayCoordinator.RefundState.SUCCEEDED);assertThat(h.store.row.refunded).isEqualTo(500);assertThat(h.store.row.state).isEqualTo(WeChatPayCoordinator.State.PAID);assertThat(h.events.types).as("coordinator must not publish after store commit").isEmpty();}
 @Test void unknownRefundQueryConvergesToRejectedAndReleasesAmount(){Harness h=unknownRefund();h.port.refundQuery=new WeChatPayPort.RefundObservation("R1","ORDER-1",500,"CNY","REJECTED","QUERY-EV");assertThat(h.coordinator.queryRefundOriginal("R1").state()).isEqualTo(WeChatPayCoordinator.RefundState.REJECTED);assertThat(h.store.row.refunded).isZero();assertThat(h.store.row.state).isEqualTo(WeChatPayCoordinator.State.PAID);}
 @Test void refundQueryBindingMismatchFailsClosed(){Harness h=unknownRefund();h.port.refundQuery=new WeChatPayPort.RefundObservation("R1","OTHER",500,"CNY","SUCCEEDED","QUERY-EV");assertThatThrownBy(()->h.coordinator.queryRefundOriginal("R1")).hasMessage("PAYMENT_REFUND_QUERY_BINDING_CONFLICT");assertThat(h.coordinator.refundStatus("R1").state()).isEqualTo(WeChatPayCoordinator.RefundState.UNKNOWN);assertThat(h.store.row.refunded).isEqualTo(500);}
 @Test void terminalRefundQueryIsIdempotentWithoutAnotherProviderCall(){Harness h=unknownRefund();h.port.refundQuery=new WeChatPayPort.RefundObservation("R1","ORDER-1",500,"CNY","SUCCEEDED","QUERY-EV");h.coordinator.queryRefundOriginal("R1");h.coordinator.queryRefundOriginal("R1");assertThat(h.port.refundQueries).hasValue(1);assertThat(h.store.row.refunded).isEqualTo(500);}
 @Test void exhaustedRefundBudgetDoesNotCallProvider(){Harness h=unknownRefund();h.store.replaceRefundWindow("R1",0,Instant.now().plusSeconds(60));assertThatThrownBy(()->h.coordinator.queryRefundOriginal("R1")).hasMessage("PAYMENT_REFUND_QUERY_BUDGET_EXHAUSTED");assertThat(h.port.refundQueries).hasValue(0);}
 @Test void expiredRefundDeadlineDoesNotCallProvider(){Harness h=unknownRefund();h.store.replaceRefundWindow("R1",2,Instant.EPOCH);assertThatThrownBy(()->h.coordinator.queryRefundOriginal("R1")).hasMessage("PAYMENT_REFUND_QUERY_BUDGET_EXHAUSTED");assertThat(h.port.refundQueries).hasValue(0);}
 @Test void concurrentUnknownQueriesConvergeOnceWithoutDoubleRelease() throws Exception {Harness h=unknownRefund();h.port.refundQuery=new WeChatPayPort.RefundObservation("R1","ORDER-1",500,"CNY","SUCCEEDED","QUERY-EV");h.port.refundQueryReady=new CountDownLatch(2);h.port.refundQueryRelease=new CountDownLatch(1);ExecutorService pool=Executors.newFixedThreadPool(2);try{Future<WeChatPayCoordinator.RefundView> one=pool.submit(()->h.coordinator.queryRefundOriginal("R1"));Future<WeChatPayCoordinator.RefundView> two=pool.submit(()->h.coordinator.queryRefundOriginal("R1"));assertThat(h.port.refundQueryReady.await(2,TimeUnit.SECONDS)).isTrue();h.port.refundQueryRelease.countDown();assertThat(one.get(2,TimeUnit.SECONDS).state()).isEqualTo(WeChatPayCoordinator.RefundState.SUCCEEDED);assertThat(two.get(2,TimeUnit.SECONDS).state()).isEqualTo(WeChatPayCoordinator.RefundState.SUCCEEDED);assertThat(h.store.row.refunded).isEqualTo(500);assertThat(h.store.row.state).isEqualTo(WeChatPayCoordinator.State.PAID);}finally{pool.shutdownNow();}}
 @Test void explicitTransitionMatrixProtectsTerminalStates(){assertThat(JdbcWeChatPayStore.allowed(WeChatPayCoordinator.State.PAID,WeChatPayCoordinator.State.REJECTED)).isFalse();assertThat(JdbcWeChatPayStore.allowed(WeChatPayCoordinator.State.CLOSED,WeChatPayCoordinator.State.PAID)).isFalse();assertThat(JdbcWeChatPayStore.allowed(WeChatPayCoordinator.State.REJECTED,WeChatPayCoordinator.State.PAID)).isFalse();}
 @Test void formalBuyerCannotCreateOrReadAnotherSubjectsPayment(){MemoryStore s=new MemoryStore();WeChatPayCoordinator c=new WeChatPayCoordinator(new Port(new WeChatPayPort.Unknown("OFF")),s,o->S,2,AUTH,new Events());assertThatThrownBy(()->c.createForBuyer(new WeChatPayCoordinator.CreateCommand("ORDER-1",D),"OTHER")).hasMessage("PAYMENT_ORDER_OWNERSHIP_CONFLICT");c.createForBuyer(new WeChatPayCoordinator.CreateCommand("ORDER-1",D),"BUYER-1");assertThatThrownBy(()->c.statusForBuyer("ORDER-1","OTHER")).hasMessage("PAYMENT_ORDER_OWNERSHIP_CONFLICT");}
 @Test void paymentRecoveryHandlerRetriesDisabledProviderAndStaleTaskMakesZeroCalls(){MemoryStore s=new MemoryStore();Port p=new Port(new WeChatPayPort.Unknown("OFF"));WeChatPayCoordinator c=new WeChatPayCoordinator(p,s,o->S,2,AUTH,new Events());c.create(new WeChatPayCoordinator.CreateCommand("ORDER-1",D));var handler=new WeChatPaymentRecoveryHandler(c);long version=c.statusForRecovery("ORDER-1").version();assertThat(handler.execute(task("ORDER-1","WECHAT_PAYMENT_QUERY",version))).isEqualTo(com.huarenzaimeng.api.recovery.RecoveryTaskWorker.Outcome.RETRY);assertThat(p.queryCalls).hasValue(1);assertThat(handler.execute(task("ORDER-1","WECHAT_PAYMENT_QUERY",version-1))).isEqualTo(com.huarenzaimeng.api.recovery.RecoveryTaskWorker.Outcome.SUCCEEDED);assertThat(p.queryCalls).hasValue(1);}
 @Test void refundRecoveryHandlerRetriesDisabledProviderAndStaleTaskMakesZeroCalls(){Harness h=unknownRefund();var handler=new WeChatRefundRecoveryHandler(h.coordinator);long version=h.coordinator.statusForRecovery("ORDER-1").version();assertThat(handler.execute(task("R1","WECHAT_REFUND_QUERY",version))).isEqualTo(com.huarenzaimeng.api.recovery.RecoveryTaskWorker.Outcome.RETRY);assertThat(h.port.refundQueries).hasValue(1);assertThat(handler.execute(task("R1","WECHAT_REFUND_QUERY",version-1))).isEqualTo(com.huarenzaimeng.api.recovery.RecoveryTaskWorker.Outcome.SUCCEEDED);assertThat(h.port.refundQueries).hasValue(1);}
 private static com.huarenzaimeng.api.recovery.RecoveryTaskStore.Task task(String ref,String op,long version){Instant now=Instant.now();return new com.huarenzaimeng.api.recovery.RecoveryTaskStore.Task("TASK-1",ref,op,version,com.huarenzaimeng.api.recovery.RecoveryTaskStore.State.LEASED,2,now.plusSeconds(60),now,"worker-1",now.plusSeconds(30),2,null,null);}
 private static Harness unknownRefund(){MemoryStore s=new MemoryStore();Port p=new Port(new WeChatPayPort.Accepted("WX","PREPAY_CREATED","EV"));Events e=new Events();WeChatPayCoordinator c=new WeChatPayCoordinator(p,s,o->S,5,AUTH,e);c.create(new WeChatPayCoordinator.CreateCommand("ORDER-1",D));s.row.state=WeChatPayCoordinator.State.PAID;p.result=new WeChatPayPort.Unknown("TIMEOUT");c.refund(new WeChatPayPort.Refund("ORDER-1","R1",500,"1".repeat(64)));return new Harness(c,s,p,e);}
 record Harness(WeChatPayCoordinator coordinator,MemoryStore store,Port port,Events events){}
 private static WeChatPayPort.VerifiedNotification notice(String id,String digest,long amount,String state,String app,String mch,String cert){return new WeChatPayPort.VerifiedNotification(id,digest,app,mch,cert,"ORDER-1","WX",amount,"CNY",state,Instant.now(),"EVN");}private static WeChatPayPort.NotificationEnvelope env(String id){return new WeChatPayPort.NotificationEnvelope(id,"1","n","s","body");}
 static final class Port implements WeChatPayPort{final AtomicInteger calls=new AtomicInteger(),queryCalls=new AtomicInteger(),refundQueries=new AtomicInteger();Result result;UnifiedOrder last;NotificationResult notice=new NotificationUnknown("NONE");RefundQueryResult refundQuery=new RefundQueryUnknown("NONE");CountDownLatch refundQueryReady,refundQueryRelease;Port(Result r){result=r;}public Result unifiedOrder(UnifiedOrder c){last=c;calls.incrementAndGet();return result;}public NotificationResult verifyAndDecrypt(NotificationEnvelope e){return notice;}public Result query(String o){queryCalls.incrementAndGet();return result;}public Result close(String o){return result;}public Result refund(Refund r){return result;}public RefundQueryResult queryRefundOriginal(String r){refundQueries.incrementAndGet();if(refundQueryReady!=null){refundQueryReady.countDown();try{if(!refundQueryRelease.await(2,TimeUnit.SECONDS))throw new IllegalStateException("REFUND_QUERY_TEST_TIMEOUT");}catch(InterruptedException interrupted){Thread.currentThread().interrupt();throw new IllegalStateException(interrupted);}}return refundQuery;}}
 static final class Events implements BusinessEventStore{final List<BusinessEventLinker.Type> types=new ArrayList<>();public void append(String o,BusinessEventLinker.Type t,String r,String d,Instant at){types.add(t);}public void bindSupportCase(String c,String o){}}
 static final class MemoryStore implements WeChatPayCoordinator.Store{
  Row row;final Map<String,String> notices=new HashMap<>();final Map<String,WeChatPayCoordinator.RefundView> refunds=new HashMap<>();
  public WeChatPayCoordinator.Begin begin(PaymentOrderSnapshotPort.Snapshot s,String d,int b,Instant deadline){if(row!=null)return same(row,s,d)?WeChatPayCoordinator.Begin.REPLAY:WeChatPayCoordinator.Begin.CONFLICT;row=new Row(s,d,b,deadline);return WeChatPayCoordinator.Begin.CREATED;}
  private boolean same(Row r,PaymentOrderSnapshotPort.Snapshot s,String d){return r.digest.equals(d)&&r.s.buyerSubjectRef().equals(s.buyerSubjectRef())&&r.s.quoteRef().equals(s.quoteRef())&&r.s.priceSnapshotDigest().equals(s.priceSnapshotDigest())&&r.s.amountMinor()==s.amountMinor()&&r.s.currency().equals(s.currency());}
  public WeChatPayCoordinator.View require(String o){return row.view();}
  public void providerResult(String o,String p,WeChatPayCoordinator.State s,String e){if(JdbcWeChatPayStore.allowed(row.state,s)){row.provider=p;row.state=s;row.evidence=e;row.version++;}}
  public void observation(String o,WeChatPayCoordinator.State s,String e){providerResult(o,null,s,e);}
  public WeChatPayCoordinator.NotificationDisposition receiveNotification(WeChatPayPort.VerifiedNotification n,WeChatPayCoordinator.State s){String old=notices.putIfAbsent(n.notificationId(),n.notificationDigest());if(old!=null)return old.equals(n.notificationDigest())?WeChatPayCoordinator.NotificationDisposition.REPLAY:WeChatPayCoordinator.NotificationDisposition.CONFLICT;providerResult(n.merchantOrderRef(),n.providerRef(),s,n.evidenceRef());return WeChatPayCoordinator.NotificationDisposition.ACCEPTED;}
  public void consumeQueryBudget(String o){row.budget--;}
  public WeChatPayCoordinator.Begin beginRefund(String o,String r,String d,long a,int budget,Instant deadline){WeChatPayCoordinator.RefundView old=refunds.get(r);if(old!=null)return old.requestDigest().equals(d)&&old.amountMinor()==a&&old.merchantOrderRef().equals(o)?WeChatPayCoordinator.Begin.REPLAY:WeChatPayCoordinator.Begin.CONFLICT;if(row.state!=WeChatPayCoordinator.State.PAID||row.refunded+a>row.s.amountMinor())return WeChatPayCoordinator.Begin.CONFLICT;refunds.put(r,new WeChatPayCoordinator.RefundView(r,o,d,a,WeChatPayCoordinator.RefundState.PENDING,row.state,budget,deadline,Instant.now()));row.refunded+=a;row.state=WeChatPayCoordinator.State.REFUND_PROCESSING;return WeChatPayCoordinator.Begin.CREATED;}
  public WeChatPayCoordinator.RefundView refundResult(String o,String r,WeChatPayPort.Result result){var old=requireRefund(r);var state=result instanceof WeChatPayPort.Accepted?WeChatPayCoordinator.RefundState.SUCCEEDED:result instanceof WeChatPayPort.Rejected?WeChatPayCoordinator.RefundState.REJECTED:WeChatPayCoordinator.RefundState.UNKNOWN;if(state==WeChatPayCoordinator.RefundState.REJECTED){row.refunded-=old.amountMinor();row.state=old.originalPaymentState();}else if(state==WeChatPayCoordinator.RefundState.UNKNOWN)row.state=WeChatPayCoordinator.State.REFUND_PROCESSING;else row.state=row.refunded==row.s.amountMinor()?WeChatPayCoordinator.State.REFUNDED:WeChatPayCoordinator.State.PAID;var next=new WeChatPayCoordinator.RefundView(r,o,old.requestDigest(),old.amountMinor(),state,old.originalPaymentState(),old.queryBudgetRemaining(),old.queryDeadline(),Instant.now());refunds.put(r,next);return next;}
  public synchronized WeChatPayCoordinator.RefundView refundObservation(String r,WeChatPayCoordinator.RefundState observed,String evidence){var old=requireRefund(r);if(old.state()!=WeChatPayCoordinator.RefundState.UNKNOWN||observed==WeChatPayCoordinator.RefundState.UNKNOWN)return old;if(observed==WeChatPayCoordinator.RefundState.REJECTED){row.refunded-=old.amountMinor();row.state=old.originalPaymentState();}else if(observed==WeChatPayCoordinator.RefundState.SUCCEEDED)row.state=row.refunded==row.s.amountMinor()?WeChatPayCoordinator.State.REFUNDED:WeChatPayCoordinator.State.PAID;else throw new WeChatPayCoordinator.Conflict("PAYMENT_REFUND_QUERY_STATE_INVALID");var next=new WeChatPayCoordinator.RefundView(r,old.merchantOrderRef(),old.requestDigest(),old.amountMinor(),observed,old.originalPaymentState(),old.queryBudgetRemaining(),old.queryDeadline(),Instant.now());refunds.put(r,next);return next;}
  public synchronized void consumeRefundQueryBudget(String r){var old=requireRefund(r);if(old.state()!=WeChatPayCoordinator.RefundState.UNKNOWN||old.queryBudgetRemaining()<=0||Instant.now().isAfter(old.queryDeadline()))throw new WeChatPayCoordinator.Conflict("PAYMENT_REFUND_QUERY_BUDGET_EXHAUSTED");refunds.put(r,new WeChatPayCoordinator.RefundView(r,old.merchantOrderRef(),old.requestDigest(),old.amountMinor(),old.state(),old.originalPaymentState(),old.queryBudgetRemaining()-1,old.queryDeadline(),Instant.now()));}
  void replaceRefundWindow(String r,int budget,Instant deadline){var old=requireRefund(r);refunds.put(r,new WeChatPayCoordinator.RefundView(r,old.merchantOrderRef(),old.requestDigest(),old.amountMinor(),old.state(),old.originalPaymentState(),budget,deadline,Instant.now()));}
  public WeChatPayCoordinator.RefundView requireRefund(String r){var v=refunds.get(r);if(v==null)throw new WeChatPayCoordinator.Conflict("PAYMENT_REFUND_NOT_FOUND");return v;}
 }
 static final class Row{PaymentOrderSnapshotPort.Snapshot s;final String digest;int budget;Instant deadline;String provider,evidence;long refunded,version=1;WeChatPayCoordinator.State state=WeChatPayCoordinator.State.NEW;Row(PaymentOrderSnapshotPort.Snapshot s,String d,int b,Instant x){this.s=s;digest=d;budget=b;deadline=x;}WeChatPayCoordinator.View view(){return new WeChatPayCoordinator.View(s.merchantOrderRef(),digest,s.buyerSubjectRef(),s.quoteRef(),s.priceSnapshotDigest(),s.amountMinor(),s.currency(),provider,state,evidence,budget,deadline,refunded,version,Instant.now());}}
}
