package com.huarenzaimeng.api.topup;
import com.huarenzaimeng.api.BusinessEventStore;import com.huarenzaimeng.core.BusinessEventLinker;import org.junit.jupiter.api.Test;import java.time.Instant;import java.util.*;import java.util.concurrent.atomic.AtomicInteger;import static org.assertj.core.api.Assertions.*;
class TopupCoordinatorTest {
 private static final String D="a".repeat(64);private static final TopupEligibilityPort.Snapshot S=new TopupEligibilityPort.Snapshot("ORDER-1","BUYER-1","SKU-1","017 1234 5678",10000,"BDT","b".repeat(64));
 @Test void submitUsesCompleteTrustedSnapshotAndLatchesOnce(){Store s=new Store();Port p=new Port(new TopupProviderPort.Unknown("OFF"));Events e=new Events();TopupCoordinator c=new TopupCoordinator(p,s,o->S,2,e);var cmd=new TopupCoordinator.SubmitCommand("ORDER-1","REQ-1",D);c.submit(cmd);c.submit(cmd);assertThat(p.submits).hasValue(1);assertThat(p.last.recipient()).isEqualTo("8801712345678");assertThat(e.types).as("coordinator must not publish after store commit").isEmpty();s.row.trusted=new TopupEligibilityPort.Snapshot("ORDER-1","OTHER","SKU-1","01712345678",10000,"BDT","b".repeat(64));assertThatThrownBy(()->c.submit(cmd)).hasMessage("TOPUP_IDEMPOTENCY_CONFLICT");}
 @Test void unknownOrStaleBalanceFailsClosed(){Store s=new Store();s.balanceReady=false;TopupCoordinator c=new TopupCoordinator(new Port(new TopupProviderPort.Unknown("OFF")),s,o->S,2,new Events());assertThatThrownBy(()->c.submit(new TopupCoordinator.SubmitCommand("ORDER-1","REQ-1",D))).hasMessage("TOPUP_BALANCE_UNKNOWN");}
 @Test void callbackBindingAndTerminalMatrixCannotOverwriteDelivered(){Store s=new Store();Port p=new Port(new TopupProviderPort.Accepted("P1","PROCESSING","EV"));Events e=new Events();TopupCoordinator c=new TopupCoordinator(p,s,o->S,2,e);c.submit(new TopupCoordinator.SubmitCommand("ORDER-1","REQ-1",D));p.callback=cb("C1","c".repeat(64),10000L,"BDT","SKU-1","01712345678","DELIVERED");assertThat(c.callback(env("C1")).state()).isEqualTo(TopupCoordinator.State.DELIVERED);p.callback=cb("C2","d".repeat(64),10000L,"BDT","SKU-1","01712345678","REJECTED");assertThat(c.callback(env("C2")).state()).isEqualTo(TopupCoordinator.State.DELIVERED);assertThat(e.types).as("coordinator must not publish after store commit").isEmpty();assertThat(JdbcTopupStore.allowed(TopupCoordinator.State.REJECTED,TopupCoordinator.State.DELIVERED)).isFalse();assertThat(JdbcTopupStore.allowed(TopupCoordinator.State.RECONCILIATION_REQUIRED,TopupCoordinator.State.DELIVERED)).isFalse();}
 @Test void balanceObservationIsPersistedBeforeCoverageDecision(){Store s=new Store();Port p=new Port(new TopupProviderPort.Unknown("TIMEOUT"));p.balance=new TopupProviderPort.BalanceObserved(12000,"BDT","BAL",Instant.now());TopupCoordinator c=new TopupCoordinator(p,s,o->S,1,new Events());assertThat(c.reconcileBalance("BDT").state()).isEqualTo(TopupCoordinator.BalanceState.COVERED);assertThat(s.confirmedBalance).isEqualTo(12000);}
 @Test void formalBuyerCannotSubmitOrReadAnotherSubjectsTopup(){Store s=new Store();TopupCoordinator c=new TopupCoordinator(new Port(new TopupProviderPort.Unknown("OFF")),s,o->S,2,new Events());assertThatThrownBy(()->c.submitForBuyer(new TopupCoordinator.SubmitCommand("ORDER-1","REQ-1",D),"OTHER")).hasMessage("TOPUP_ORDER_OWNERSHIP_CONFLICT");c.submitForBuyer(new TopupCoordinator.SubmitCommand("ORDER-1","REQ-1",D),"BUYER-1");assertThatThrownBy(()->c.statusForBuyer("ORDER-1","OTHER")).hasMessage("TOPUP_ORDER_OWNERSHIP_CONFLICT");}
 @Test void recoveryHandlerRetriesDisabledProviderAndStaleTaskMakesZeroCalls(){Store s=new Store();Port p=new Port(new TopupProviderPort.Unknown("OFF"));TopupCoordinator c=new TopupCoordinator(p,s,o->S,2,new Events());c.submit(new TopupCoordinator.SubmitCommand("ORDER-1","REQ-1",D));var handler=new WinlaTopupRecoveryHandler(c);long version=c.statusForRecovery("ORDER-1").version();assertThat(handler.execute(task(version))).isEqualTo(com.huarenzaimeng.api.recovery.RecoveryTaskWorker.Outcome.RETRY);assertThat(p.queries).hasValue(1);assertThat(handler.execute(task(version-1))).isEqualTo(com.huarenzaimeng.api.recovery.RecoveryTaskWorker.Outcome.SUCCEEDED);assertThat(p.queries).hasValue(1);}
 private static com.huarenzaimeng.api.recovery.RecoveryTaskStore.Task task(long version){Instant now=Instant.now();return new com.huarenzaimeng.api.recovery.RecoveryTaskStore.Task("TASK-1","ORDER-1","WINLA_TOPUP_QUERY",version,com.huarenzaimeng.api.recovery.RecoveryTaskStore.State.LEASED,2,now.plusSeconds(60),now,"worker-1",now.plusSeconds(30),2,null,null);}
 private static TopupProviderPort.VerifiedCallback cb(String id,String digest,Long amount,String currency,String sku,String recipient,String state){return new TopupProviderPort.VerifiedCallback(id,digest,"ORDER-1","P1",state,amount,currency,sku,recipient,Instant.now(),"EV");}private static TopupProviderPort.CallbackEnvelope env(String id){return new TopupProviderPort.CallbackEnvelope(id,"1","n","s","body");}
 static final class Port implements TopupProviderPort{final AtomicInteger submits=new AtomicInteger(),queries=new AtomicInteger();Result result;Command last;BalanceResult balance=new BalanceUnknown("NONE");CallbackResult callback=new CallbackUnknown("NONE");Port(Result r){result=r;}public Result submit(Command c){last=c;submits.incrementAndGet();return result;}public Result query(String p,String o){queries.incrementAndGet();return result;}public BalanceResult balance(){return balance;}public CallbackResult verifyCallback(CallbackEnvelope e){return callback;}}
 static final class Events implements BusinessEventStore{final List<BusinessEventLinker.Type> types=new ArrayList<>();public void append(String o,BusinessEventLinker.Type t,String r,String d,Instant at){types.add(t);}public void bindSupportCase(String c,String o){}}
 static final class Store implements TopupCoordinator.Store{Row row;int reservations;boolean balanceReady=true;long confirmedBalance=100000;final Map<String,String> callbacks=new HashMap<>();public TopupCoordinator.Begin beginAndReserve(TopupProviderPort.Command c,TopupEligibilityPort.Snapshot trusted,int b){if(row!=null)return same(row,c,trusted)?TopupCoordinator.Begin.REPLAY:TopupCoordinator.Begin.CONFLICT;if(!balanceReady)throw new TopupCoordinator.Conflict("TOPUP_BALANCE_UNKNOWN");if(confirmedBalance-reservedTotal(c.targetCurrency())<c.faceValueMinor())throw new TopupCoordinator.Conflict("TOPUP_BALANCE_INSUFFICIENT");row=new Row(c,trusted,b);reservations++;return TopupCoordinator.Begin.CREATED;}private boolean same(Row r,TopupProviderPort.Command c,TopupEligibilityPort.Snapshot s){return r.command.requestDigest().equals(c.requestDigest())&&r.command.requestRef().equals(c.requestRef())&&r.trusted.entitlementDigest().equals(s.entitlementDigest())&&r.trusted.buyerSubjectRef().equals(s.buyerSubjectRef())&&r.command.providerSku().equals(c.providerSku())&&r.command.recipient().equals(c.recipient())&&r.command.faceValueMinor()==c.faceValueMinor()&&r.command.targetCurrency().equals(c.targetCurrency());}public TopupCoordinator.View require(String o){return row.view();}public void submissionResult(String o,String p,TopupCoordinator.State s,String e){advance(s);row.provider=p;}public void submissionRejectedAndRelease(String o,String e){advance(TopupCoordinator.State.REJECTED);reservations--;}public void consumeUnknownQuery(String o){row.budget--;}public void observation(String o,TopupCoordinator.State s,String e){advance(s);}public TopupCoordinator.CallbackDisposition callback(TopupProviderPort.VerifiedCallback c,TopupCoordinator.State s){String old=callbacks.putIfAbsent(c.callbackId(),c.callbackDigest());if(old!=null){if(!old.equals(c.callbackDigest()))throw new TopupCoordinator.Conflict("TOPUP_CALLBACK_ID_CONFLICT");return TopupCoordinator.CallbackDisposition.REPLAY;}advance(s);row.provider=c.providerRef();return TopupCoordinator.CallbackDisposition.ACCEPTED;}private void advance(TopupCoordinator.State s){if(JdbcTopupStore.allowed(row.state,s))row.state=s;}public void reconciliationRequired(String o,String e){advance(TopupCoordinator.State.RECONCILIATION_REQUIRED);}public long reservedTotal(String c){return reservations==0?0:row.command.faceValueMinor();}public void recordBalanceObservation(String p,String c,long amount,Instant at,String e){balanceReady=true;confirmedBalance=amount;}}
 static final class Row{final TopupProviderPort.Command command;TopupEligibilityPort.Snapshot trusted;int budget;String provider,evidence;long version=1;TopupCoordinator.State state=TopupCoordinator.State.RESERVED;Row(TopupProviderPort.Command c,TopupEligibilityPort.Snapshot s,int b){command=c;trusted=s;budget=b;}TopupCoordinator.View view(){return new TopupCoordinator.View(command.merchantOrderRef(),command.requestRef(),command.requestDigest(),trusted.buyerSubjectRef(),command.providerSku(),command.recipient(),trusted.entitlementDigest(),provider,state,command.faceValueMinor(),command.targetCurrency(),budget,evidence,version,Instant.now());}}
}
