package com.huarenzaimeng.api.topup;

import org.junit.jupiter.api.Test;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.*;
import static org.assertj.core.api.Assertions.*;

class WinlaTopupAdapterContractTest {
    static final Instant NOW=Instant.parse("2026-08-18T00:00:00Z");static final String DIGEST="a".repeat(64);
    @Test void adapterAloneNormalizesLeadingZeroAmountAndPersistsValidatedAttempt(){MemoryStore store=new MemoryStore();FixtureTransport transport=new FixtureTransport(raw("REQ-1","000100.00","CNY","SKU-1","01712345678",DIGEST));var adapter=adapter(transport,store);var result=adapter.submit(command());assertThat(result).isInstanceOf(TopupProviderPort.Accepted.class);assertThat(store.last.normalizedAmountMinor()).isEqualTo(10000);assertThat(store.last.normalizedCurrency()).isEqualTo("CNY");assertThat(store.last.providerAmountRaw()).isEqualTo("000100.00");}
    @Test void invalidScaleHugeAmountAndCurrencyFailClosed(){for(String amount:List.of("100.001","999999999999999999999999.00")){MemoryStore store=new MemoryStore();assertThat(adapter(new FixtureTransport(raw("REQ-"+amount,amount,"CNY","SKU-1","01712345678",DIGEST)),store).submit(command())).isInstanceOf(TopupProviderPort.Unknown.class);assertThat(store.last.normalizationStatus()).isEqualTo(ProviderExchangeStore.NormalizationStatus.INVALID_AMOUNT);}MemoryStore store=new MemoryStore();assertThat(adapter(new FixtureTransport(raw("REQ-X","100.00","USD","SKU-1","01712345678",DIGEST)),store).submit(command())).isInstanceOf(TopupProviderPort.Unknown.class);assertThat(store.last.normalizationStatus()).isEqualTo(ProviderExchangeStore.NormalizationStatus.INVALID_CURRENCY);}
    @Test void skuAndRecipientMismatchFailClosedAndCannotBecomeDelivered(){for(WinlaTopupAdapter.RawResult raw:List.of(raw("REQ-S","100.00","CNY","OTHER","01712345678",DIGEST),raw("REQ-R","100.00","CNY","SKU-1","01812345678",DIGEST))){MemoryStore store=new MemoryStore();assertThat(adapter(new FixtureTransport(raw),store).submit(command())).isInstanceOf(TopupProviderPort.Unknown.class);assertThat(store.last.normalizationStatus()).isEqualTo(ProviderExchangeStore.NormalizationStatus.BINDING_MISMATCH);}}
    @Test void queryAndCallbackRequireOriginalProviderOrderAmountCurrencySkuAndRecipientBinding(){MemoryStore store=new MemoryStore();FixtureTransport transport=new FixtureTransport(raw("REQ-1","100.00","CNY","SKU-1","01712345678",DIGEST));var adapter=adapter(transport,store);assertThat(adapter.submit(command())).isInstanceOf(TopupProviderPort.Accepted.class);transport.next=raw("QUERY-1","100.00","CNY","SKU-1","01712345678","b".repeat(64));assertThat(adapter.query("P-1","ORDER-1")).isInstanceOf(TopupProviderPort.Accepted.class);transport.callback=new WinlaTopupAdapter.RawCallback("CB-REQ","CB-1","c".repeat(64),"ORDER-1","P-1","DELIVERED","10000",WinlaTopupAdapter.AmountUnit.MINOR,"CNY","SKU-1","01812345678","d".repeat(64),NOW,"EV");assertThat(adapter.verifyCallback(new TopupProviderPort.CallbackEnvelope("CB-1","1","N","S","BODY"))).isInstanceOf(TopupProviderPort.CallbackUnknown.class);}
    @Test void eachQueryBindingMismatchFailsClosed(){MemoryStore store=new MemoryStore();FixtureTransport transport=new FixtureTransport(raw("REQ-1","100.00","CNY","SKU-1","01712345678",DIGEST));var adapter=adapter(transport,store);adapter.submit(command());List<WinlaTopupAdapter.RawResult> drift=List.of(raw("Q-AMT","101.00","CNY","SKU-1","01712345678","1".repeat(64)),raw("Q-CUR","100.00","USD","SKU-1","01712345678","2".repeat(64)),raw("Q-SKU","100.00","CNY","OTHER","01712345678","3".repeat(64)),raw("Q-PHONE","100.00","CNY","SKU-1","01812345678","4".repeat(64)),new WinlaTopupAdapter.RawResult("Q-PROVIDER","ORDER-1","P-2","PROCESSING","100.00",WinlaTopupAdapter.AmountUnit.MAJOR,"CNY","SKU-1","01712345678","5".repeat(64),NOW,"EV",null),new WinlaTopupAdapter.RawResult("Q-ORDER","OTHER","P-1","PROCESSING","100.00",WinlaTopupAdapter.AmountUnit.MAJOR,"CNY","SKU-1","01712345678","6".repeat(64),NOW,"EV",null));for(var raw:drift){transport.next=raw;assertThat(adapter.query("P-1","ORDER-1")).isInstanceOf(TopupProviderPort.Unknown.class);}}
    @Test void sameProviderRequestWithDifferentRawResponseIsConflict(){MemoryStore store=new MemoryStore();FixtureTransport transport=new FixtureTransport(raw("REQ-1","100.00","CNY","SKU-1","01712345678",DIGEST));var adapter=adapter(transport,store);adapter.submit(command());transport.next=raw("REQ-1","100.00","CNY","SKU-1","01712345678","b".repeat(64));assertThatThrownBy(()->adapter.submit(command())).hasMessage("PROVIDER_REQUEST_REF_CONFLICT");}
    @Test void signedCallbackCanBindDocumentedFieldsWithoutInventingPhoneOrSku(){MemoryStore store=new MemoryStore();FixtureTransport transport=new FixtureTransport(raw("REQ-1","100.00","CNY",null,null,DIGEST));var adapter=adapter(transport,store);assertThat(adapter.submit(command())).isInstanceOf(TopupProviderPort.Accepted.class);transport.callback=new WinlaTopupAdapter.RawCallback("CB-REQ","CB-1","c".repeat(64),"ORDER-1","P-1","DELIVERED","10000",WinlaTopupAdapter.AmountUnit.MINOR,"CNY",null,null,"d".repeat(64),NOW,"EV");assertThat(adapter.verifyCallback(new TopupProviderPort.CallbackEnvelope("ignored","","","","signed-form"))).isInstanceOf(TopupProviderPort.VerifiedCallback.class);}
    @Test void adapterHasNoRawSecretLoggingOrEventPublication() throws Exception {String source=Files.readString(Path.of("src/main/java/com/huarenzaimeng/api/topup/WinlaTopupAdapter.java"));assertThat(source).doesNotContain("Logger","System.out","BusinessEventStore","rawResponseBody");}
    private static WinlaTopupAdapter adapter(FixtureTransport t,MemoryStore s){return new WinlaTopupAdapter(t,true,s,new WinlaTopupAdapter.Contract("FAKE-V1","CNY",2));}
    private static TopupProviderPort.Command command(){return new TopupProviderPort.Command("ORDER-1","LOCAL-REQ","SKU-1","01712345678",10000,"CNY","e".repeat(64));}
    private static WinlaTopupAdapter.RawResult raw(String request,String amount,String currency,String sku,String recipient,String digest){return new WinlaTopupAdapter.RawResult(request,"ORDER-1","P-1","PROCESSING",amount,WinlaTopupAdapter.AmountUnit.MAJOR,currency,sku,recipient,digest,NOW,"EV",null);}
    static final class FixtureTransport implements WinlaTopupAdapter.Transport{WinlaTopupAdapter.RawResult next;WinlaTopupAdapter.RawCallback callback;FixtureTransport(WinlaTopupAdapter.RawResult r){next=r;}public WinlaTopupAdapter.RawResult submit(TopupProviderPort.Command c){return next;}public WinlaTopupAdapter.RawResult query(String p,String o){return next;}public TopupProviderPort.BalanceResult balance(){return new TopupProviderPort.BalanceUnknown("NONE");}public WinlaTopupAdapter.RawCallback verifyCallback(TopupProviderPort.CallbackEnvelope e){return callback;}}
    static final class MemoryStore implements ProviderExchangeStore{final Map<String,Attempt> rows=new HashMap<>();Attempt last;public SaveResult record(Attempt a){String key=a.providerCode()+"|"+a.providerRequestRef();Attempt old=rows.putIfAbsent(key,a);if(old!=null&&!old.equals(a))throw new Conflict("PROVIDER_REQUEST_REF_CONFLICT");last=a;return old==null?SaveResult.CREATED:SaveResult.REPLAY;}public Original requireOriginal(String p,String order){return rows.values().stream().filter(a->a.operation()==Operation.SUBMIT&&a.normalizationStatus()==NormalizationStatus.VALIDATED&&a.merchantOrderRef().equals(order)).findFirst().map(a->new Original(a.merchantOrderRef(),a.providerRef(),a.localAmountMinor(),a.localCurrency(),a.providerSku(),a.recipientDigest(),a.canonicalRequestDigest(),a.contractVersion())).orElseThrow(()->new Conflict("PROVIDER_ORIGINAL_EXCHANGE_NOT_FOUND"));}}
}
