<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import AppHeader from '../../components/AppHeader.vue'
import StatusNotice from '../../components/StatusNotice.vue'
import { api, apiRuntime } from '../../api/client'
import { fromQuote, isCompleteSnapshot } from '../../domain/price-snapshot'
import { freezeOrderSnapshot } from '../../domain/snapshot-flow'
import { getOrCreateCommand } from '../../domain/command-identity'
import type { QuoteSnapshot } from '../../domain/types'
const quote=ref<QuoteSnapshot|null>(null),loading=ref(true),error=ref('')
const snapshotReady=computed(()=>!!quote.value&&quote.value.valid&&isCompleteSnapshot(fromQuote(quote.value))&&Date.parse(quote.value.validUntil)>Date.now())
onMounted(async()=>{const s=uni.getStorageSync('rechargeSelection')as{maskedPhone?:string;productRef?:string};if(!s?.maskedPhone||!s?.productRef){error.value='缺少有效的号码与商品选择。';loading.value=false;return}try{quote.value=await api.createQuote(s.maskedPhone,s.productRef)}catch{error.value='价格快照读取失败。'}finally{loading.value=false}})
async function createOrder(){if(!quote.value||!snapshotReady.value)return;loading.value=true;error.value='';try{let orderRef=quote.value.orderRef;if(apiRuntime.mode==='PROJECT_MOCK_API'){const command=getOrCreateCommand(uni,`create-order:${quote.value.priceSnapshotRef}`),projection=await api.createOrder(quote.value.priceSnapshotRef,command.commandId,command.idempotencyKey);orderRef=projection.orderRef;uni.setStorageSync(`coreProjection:${orderRef}`,projection)}if(!orderRef)throw new Error('ORDER_REF_MISSING');freezeOrderSnapshot(uni,orderRef,fromQuote(quote.value));uni.navigateTo({url:`/pages/payment/status?orderRef=${encodeURIComponent(orderRef)}`})}catch{error.value='暂时无法创建订单，请稍后重试。'}finally{loading.value=false}}
const money=(n:number)=>(n/100).toFixed(2)
const displayMoney=(value:{minor:number;currency:string})=>`${value.currency==='CNY'?'¥':value.currency==='BDT'?'৳':value.currency} ${money(value.minor)}`
</script>
<template><view class="page"><AppHeader title="确认充值" left="返回" @left="uni.navigateBack()"/><view class="content"><view class="progress"><text/><text class="active"/><text/></view><text class="step">第 2 步，共 3 步</text><view class="heading" role="heading" aria-level="1">请核对充值信息</view><StatusNotice v-if="error" tone="risk" title="暂时不能继续">{{error}}</StatusNotice><view v-if="quote" class="summary"><view><text>充值号码</text><text>{{quote.maskedPhone}}</text></view><view><text>运营商</text><text>{{quote.operatorName}}</text></view><view><text>到账金额</text><text>{{money(quote.faceValue.minor)}} {{quote.faceValue.currency}}</text></view></view><view v-if="quote" class="total-card"><text>应付总价</text><strong>{{displayMoney(quote.total)}}</strong><small>已包含全部费用</small></view><text class="notice">请确认号码无误，充值完成后通常无法撤回。</text><StatusNotice v-if="quote&&!snapshotReady" tone="risk" title="信息已更新">请返回重新获取报价后再继续。</StatusNotice></view><view class="action"><button class="primary" :disabled="!snapshotReady||loading" @click="createOrder">{{loading?'正在提交…':quote?`确认并支付 ${displayMoney(quote.total)}`:'确认并支付'}}</button></view></view></template>
<style src="../../styles/shared.css"></style><style scoped>.progress{display:flex;margin-bottom:20rpx}.progress text{height:8rpx;border-radius:8rpx;background:#d8dee7;flex:1;margin-right:12rpx}.progress text:last-child{margin-right:0}.progress .active{background:var(--brand)}.summary{margin-top:28rpx;padding:16rpx 30rpx;background:#fff;border-radius:36rpx}.summary view{display:flex;justify-content:space-between;padding:28rpx 0;border-bottom:1rpx solid var(--line)}.summary view:last-child{border:0}.summary text:first-child{color:var(--muted)}.summary text:last-child{font-weight:800}.total-card{margin-top:24rpx;padding:36rpx;background:#edf4ff;border-radius:36rpx}.total-card text,.total-card small{display:block;color:var(--muted)}.total-card strong{display:block;font-size:60rpx;color:var(--brand-strong);margin:12rpx 0}.notice{display:block;margin-top:24rpx;padding:24rpx;border-radius:24rpx;background:#fff7e9;color:var(--unknown);font-size:24rpx;line-height:1.6}</style>
