<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import AppHeader from '../../components/AppHeader.vue'
import StatusNotice from '../../components/StatusNotice.vue'
import { api } from '../../api/client'
import type { CatalogProjection, EligibilityResult } from '../../domain/types'
const phone=ref(''),loading=ref(false),operatorLoading=ref(true),error=ref(''),fieldError=ref(''),operatorError=ref(''),eligibility=ref<EligibilityResult|null>(null),catalog=ref<CatalogProjection|null>(null),supportedOperatorNames=ref<string[]>([])
const supportedOperators=computed(()=>supportedOperatorNames.value.length?supportedOperatorNames.value.join('、'):operatorLoading.value?'当前可售运营商读取中':'暂时无法确认')
const canContinue=computed(()=>eligibility.value?.outcome==='ELIGIBLE'&&catalog.value?.operatorQualification==='SUPPORTED')
const validPhone=computed(()=>/^01[3-9]\d{8}$/.test(phone.value))
async function loadOperators(){operatorLoading.value=true;operatorError.value='';try{supportedOperatorNames.value=(await api.getSupportedOperators()).map(item=>item.displayName);if(!supportedOperatorNames.value.length)throw new Error('EMPTY_OPERATOR_LIST')}catch{supportedOperatorNames.value=[];operatorError.value='暂时无法读取可售运营商，当前不能继续充值。'}finally{operatorLoading.value=false}}
onMounted(loadOperators)
async function check(){fieldError.value=validPhone.value?'':'请输入以 01 开头的 11 位孟加拉手机号。';if(fieldError.value||operatorError.value)return;loading.value=true;error.value='';eligibility.value=null;catalog.value=null;try{const result=await api.checkEligibility(phone.value);eligibility.value=result;if(result.outcome==='ELIGIBLE')catalog.value=await api.getCatalog(result.operatorCode)}catch{error.value='暂时无法识别号码或读取运营商商品，请检查网络后重试。'}finally{loading.value=false}}
function next(){if(!canContinue.value||eligibility.value?.outcome!=='ELIGIBLE')return;uni.setStorageSync('rechargeEligibility',eligibility.value);uni.navigateTo({url:'/pages/recharge/products'})}
</script>
<template><view class="page" data-page-id="UX-P010" data-page-root="recharge-select"><AppHeader title="号码与运营商" left="返回" @left="uni.navigateBack()"/><view class="content"><view class="heading" role="heading" aria-level="1">输入孟加拉手机号</view><text class="desc">系统会识别当前运营商与可售商品</text><view class="supported-line">支持 {{supportedOperators}} 运营商</view><StatusNotice v-if="operatorError" tone="risk" title="运营商列表读取失败">{{operatorError}}<button class="identify" :disabled="operatorLoading" @click="loadOperators">重新读取</button></StatusNotice><view class="phone-card"><text class="field-label">手机号码</text><view class="phone-row"><input v-model="phone" type="number" maxlength="11" placeholder="01712345678" @input="fieldError=''"/></view><text class="field-help">请输入以 01 开头的 11 位孟加拉手机号</text><text v-if="fieldError" class="field-error" role="alert">{{fieldError}}</text><button class="identify" :disabled="loading||operatorLoading||!!operatorError||!validPhone" @click="check">{{loading?'正在识别…':'识别运营商'}}</button></view><StatusNotice v-if="eligibility?.outcome==='UNKNOWN'" tone="unknown" title="暂时无法确认运营商">请检查号码，或稍后重新识别；当前不会进入商品选择。</StatusNotice><StatusNotice v-if="catalog?.operatorQualification==='UNSUPPORTED'" tone="risk" title="当前暂不支持该运营商">该运营商尚无可售商品，请修改号码。</StatusNotice><StatusNotice v-if="catalog?.operatorQualification==='UNKNOWN'" tone="unknown" title="暂时无法确认是否支持">当前不能继续选择商品。</StatusNotice><StatusNotice v-if="error" tone="risk" title="识别失败">{{error}}</StatusNotice><view v-if="canContinue&&eligibility?.outcome==='ELIGIBLE'" class="result-card"><text class="operator-icon">号码</text><view><text class="operator-name">{{eligibility.operatorName}}</text><text>孟加拉 · 当前可售运营商</text><small>支持充值 · 商品可查询</small></view></view><view class="tip-card"><text>请确认充值号码</text><small>充值提交后无法更改接收号码</small></view></view><view class="action"><button class="primary" :disabled="!canContinue" @click="next">下一步</button></view></view></template>
<style src="../../styles/shared.css"></style><style scoped>.supported-line{margin-top:22rpx;padding:18rpx 22rpx;border-radius:20rpx;background:#eaf2ff;color:var(--brand);font-size:22rpx;line-height:1.5}.phone-card{margin-top:24rpx;padding:30rpx;border-radius:32rpx;background:#fff;box-shadow:0 12rpx 30rpx rgba(23,52,95,.06)}.field-label,.field-help,.field-error{display:block}.field-label{color:var(--muted);font-size:23rpx}.phone-row{margin-top:18rpx;display:flex}.phone-row input{min-height:92rpx;display:flex;align-items:center;flex:1;padding:0 24rpx;border:3rpx solid var(--brand);border-radius:22rpx;font-size:32rpx;font-weight:700}.field-help{margin-top:16rpx;color:var(--muted);font-size:21rpx}.field-error{margin-top:10rpx;color:#b42318;font-size:21rpx}.identify{width:100%;min-height:78rpx;margin-top:18rpx;color:var(--brand);font-weight:800;text-align:center}.result-card{margin-top:24rpx;padding:30rpx;display:flex;align-items:center;border-radius:32rpx;background:#fff}.operator-icon{width:96rpx;height:96rpx;margin-right:24rpx;display:flex;align-items:center;justify-content:center;border-radius:50%;background:#eaf2ff;font-size:44rpx}.result-card view{flex:1}.result-card view text,.result-card small{display:block}.operator-name{font-size:34rpx;font-weight:800}.result-card view>text:not(.operator-name){margin-top:7rpx;color:var(--muted);font-size:22rpx}.result-card small{margin-top:14rpx;color:#19865d;font-weight:700}.tip-card{margin-top:24rpx;padding:24rpx;border-radius:24rpx;background:#fff8e8;color:#5e4b24}.tip-card text,.tip-card small{display:block}.tip-card text{font-weight:800}.tip-card small{margin-top:7rpx;color:#806e49}</style>
