<script setup lang="ts">
import { computed, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import AppHeader from '../../components/AppHeader.vue'
import { api } from '../../api/client'
import { loadAuthorizedOrderList } from '../../domain/order-list'
import type { OrderSummary } from '../../domain/types'
const orders=ref<OrderSummary[]>([]),loading=ref(false),error=ref(''),needsAccess=ref(false)
const filter=ref<'ALL'|'ACTIVE'|'COMPLETED'>('ALL')
const completedStates=new Set<OrderSummary['stateCode']>(['DELIVERED','REFUNDED','CONFIRMED_NOT_DELIVERED'])
const visibleOrders=computed(()=>orders.value.filter(item=>filter.value==='ALL'||(filter.value==='COMPLETED')===completedStates.has(item.stateCode)))
const goRecovery=()=>uni.navigateTo({url:'/pages/order/recovery'})
async function load(){orders.value=[];error.value='';loading.value=true;const loaded=await loadAuthorizedOrderList(uni,current=>api.getOrders(current));orders.value=loaded.orders;needsAccess.value=loaded.session.role!=='BUYER';if(loaded.outcome==='ERROR')error.value='暂时无法读取订单，请重新登录或稍后再试。';loading.value=false}
onShow(load)
const open=(orderRef:string)=>uni.navigateTo({url:`/pages/order/detail?orderRef=${encodeURIComponent(orderRef)}`})
const status=(code:OrderSummary['stateCode'])=>({AWAITING_PAYMENT:'等待付款',PAYMENT_PROCESSING:'正在确认付款',PAID_AWAITING_TOPUP:'已付款，等待充值',TOPUP_PROCESSING:'正在充值',TOPUP_RESULT_UNKNOWN:'充值结果待确认',DELIVERED:'已到账',CONFIRMED_NOT_DELIVERED:'未到账',REFUND_PROCESSING:'退款处理中',REFUNDED:'已退款',DELIVERY_REFUND_CONFLICT_REVIEW:'结果核对中',SUPPORT_REVIEW:'客服处理中'}[code])
</script>
<template><view class="page" data-page-id="UX-P020" data-page-root="order-list"><AppHeader title="我的订单" left="我的" @left="uni.reLaunch({url:'/pages/profile/index'})"/><view class="content"><view class="heading">充值订单</view><text class="desc">仅显示当前账号的订单</text><view v-if="!needsAccess" class="filters"><button :class="{active:filter==='ALL'}" @click="filter='ALL'">全部</button><button :class="{active:filter==='ACTIVE'}" @click="filter='ACTIVE'">进行中</button><button :class="{active:filter==='COMPLETED'}" @click="filter='COMPLETED'">已完成</button></view><view v-if="needsAccess" class="card"><text class="card-title">登录后查看订单</text><text class="copy">请先登录；若更换设备或历史订单未显示，可使用找回订单。</text><button class="primary login-action" @click="uni.navigateTo({url:'/pages/auth/expired'})">微信快捷登录</button></view><view v-else-if="loading" class="card state">正在读取订单…</view><view v-else-if="error" class="card state"><text>{{error}}</text><button class="retry" @click="load">重新加载</button></view><button v-for="item in visibleOrders" :key="item.orderRef" class="card order" @click="open(item.orderRef)"><view><text class="order-ref">{{item.orderRef}}</text><text class="order-title">手机充值订单</text><text class="copy">投影版本：{{item.projectionVersion}}</text></view><text class="status">{{status(item.stateCode)}}</text><text class="arrow">›</text></button><view v-if="!needsAccess&&!loading&&!error&&!visibleOrders.length" class="card state">{{orders.length?'当前分类暂无订单':'暂无订单'}}</view><view class="recovery-card"><text class="card-title">找不到历史订单？</text><text class="copy">重新登录后仍缺失时，可以申请找回</text><button @click="goRecovery">找回订单</button></view></view></view></template>
<style src="../../styles/shared.css"></style><style scoped>.filters{margin-top:24rpx;padding:7rpx;display:grid;grid-template-columns:repeat(3,1fr);border-radius:22rpx;background:#e8eef7}.filters button{min-height:74rpx;border-radius:17rpx;color:var(--muted);text-align:center}.filters .active{background:#fff;color:var(--brand);font-weight:800}.order{width:100%;display:flex;align-items:center;gap:18rpx;text-align:left}.order>view{flex:1;min-width:0}.order-ref,.order-title,.order .copy{display:block}.order-ref{color:var(--muted);font-size:21rpx;overflow:hidden;text-overflow:ellipsis}.order-title{margin-top:12rpx;font-size:30rpx;font-weight:800}.status{padding:9rpx 14rpx;border-radius:999rpx;background:#fff3d8;color:#936211;font-size:21rpx;font-weight:800}.arrow{color:#8793a4;font-size:42rpx}.state{text-align:center}.retry,.recovery-card button{margin-top:18rpx;color:var(--brand);font-weight:800}.recovery-card{margin-top:24rpx;padding:28rpx;border-radius:28rpx;background:#fff}.login-action{margin-top:24rpx}</style>
