spring:
  flyway:
    locations: classpath:db/migration
hz:
  environment:
    name: test
    database-name: ${HZ_ENV_DATABASE_NAME}
    migration-enabled: ${HZ_ENV_MIGRATION_ENABLED:false}
    function-release-enabled: ${HZ_ENV_FUNCTION_RELEASE_ENABLED:false}
  v1-dev-data:
    enabled: false
  external-integrations:
    wechat-payment-enabled: false
    topup-provider-enabled: false
