spring:
  flyway:
    locations: classpath:db/migration,classpath:db/devdata
hz:
  environment:
    name: dev
    database-name: ${HZ_DEV_DATABASE_NAME}
    migration-enabled: true
  dev-database-name: ${HZ_DEV_DATABASE_NAME}
  v1-dev-data:
    enabled: true
  dev-function-release:
    enabled: true
  persistence:
    mode: mysql
  external-integrations:
    wechat-payment-enabled: false
    topup-provider-enabled: false
