<script setup lang="ts">
import { computed, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import AppHeader from '../../components/AppHeader.vue'
import StatusNotice from '../../components/StatusNotice.vue'
import { api } from '../../api/client'
import type { PaymentView, ReleaseOrderView } from '../../api/formal-transaction-contract'
import { projectOrderStateCopy } from '../../domain/formal-status-copy'
const orderRef=ref(''),projection=ref<ReleaseOrderView|null>(null),payment=ref<PaymentView|null>(null),loading=ref(true),paying=ref(false),error=ref(''),channelDisabled=ref(false)
const paymentReadState=ref<'IDLE'|'LOADING'|'READY'|'READ_ERROR'>('IDLE')
const paymentAvailable=computed(()=>paymentReadState.value==='READY'&&payment.value?.prepayParameters!==null&&payment.value?.prepayParameters!==undefined)
const stateLabel=computed(()=>{
  const state=projection.value?.orderState
  return projectOrderStateCopy(state).label
})
const unpaid=computed(()=>['CREATED','PAYMENT_PENDING'].includes(projection.value?.orderState||''))
const paymentStateLabel=computed(()=>({NEW:'待创建',PREPAY_CREATED:'待支付',PROCESSING:'支付处理中',PAID:'支付成功',CLOSED:'已关闭',REFUND_PROCESSING:'退款处理中',REFUNDED:'已退款',REJECTED:'支付失败',UNKNOWN:'支付结果待确认'}[payment.value?.state||'UNKNOWN']))
const navigateBack=()=>uni.navigateBack()
const viewOrder=()=>projection.value&&uni.redirectTo({url:`/pages/order/detail?orderRef=${encodeURIComponent(projection.value.orderRef)}`})
async function load(){if(!orderRef.value)return;loading.value=true;error.value='';channelDisabled.value=false;projection.value=null;payment.value=null;paymentReadState.value='LOADING';try{projection.value=await api.getCoreProjection(orderRef.value);try{payment.value=await api.getPaymentStatus(orderRef.value);paymentReadState.value='READY'}catch{payment.value=null;paymentReadState.value='READ_ERROR';error.value='支付状态暂时无法读取，已撤销旧结果；当前不会重新发起支付。'}}catch{projection.value=null;payment.value=null;paymentReadState.value='READ_ERROR';error.value='订单状态暂时无法读取，请稍后重试。'}finally{loading.value=false}}
async function queryOriginal(){if(payment.value?.state!=='UNKNOWN')return;loading.value=true;error.value='';payment.value=null;paymentReadState.value='LOADING';try{payment.value=await api.queryPaymentOriginal(orderRef.value);paymentReadState.value='READY'}catch(caught){payment.value=null;paymentReadState.value='READ_ERROR';channelDisabled.value=caught instanceof Error&&caught.message==='TRANSACTION_CHANNEL_DISABLED';error.value=channelDisabled.value?'微信支付通道当前不可用，请稍后查询原订单。':'原支付结果暂时无法确认，已撤销旧结果；当前不会重新发起支付。'}finally{loading.value=false}}
async function pay(){const params=payment.value?.prepayParameters;if(!params||paying.value)return;paying.value=true;error.value='';try{await new Promise<void>((resolve,reject)=>uni.requestPayment({provider:'wxpay',...params,success:()=>resolve(),fail:()=>reject(new Error('WECHAT_PAYMENT_NOT_COMPLETED'))}))}catch{error.value='支付未完成，未据此认定扣款成功。'}finally{paying.value=false;await load()}}
onLoad(query=>{orderRef.value=typeof query?.orderRef==='string'?decodeURIComponent(query.orderRef):'';void load()})
</script>
<template><view class="page" data-page-id="UX-P013" :data-payment-sdk="paymentAvailable?'available':'disabled-by-default'" :data-payment-read-state="paymentReadState"><AppHeader title="支付状态" left="返回" @left="navigateBack"/><view class="content"><view v-if="paymentReadState==='READ_ERROR'" class="payment-hero unavailable"><text>支付状态未确认</text><strong>暂时无法读取</strong><small>旧支付结果已撤销，不会重新发起支付</small></view><view v-else-if="unpaid&&!paymentAvailable" class="payment-hero unavailable"><text>当前暂不可支付</text><strong>未扣款</strong><small>本次支付尚未开放，请稍后再试</small></view><view v-else class="payment-hero"><text>订单进度</text><strong>{{stateLabel}}</strong><small>以订单最新状态为准</small></view><view v-if="loading" class="card">正在读取订单…</view><StatusNotice v-else-if="error" tone="risk" title="支付未完成">{{error}}</StatusNotice><template v-else-if="projection"><view class="card"><view class="kv"><text>订单号</text><text>{{projection.orderRef}}</text></view><view class="kv"><text>订单状态</text><text>{{stateLabel}}</text></view><view v-if="payment" class="kv"><text>支付状态</text><text>{{paymentStateLabel}}</text></view><view v-if="payment" class="kv"><text>应付金额</text><text>{{payment.currency}} {{(payment.amountMinor/100).toFixed(2)}}</text></view></view><StatusNotice v-if="(unpaid&&!paymentAvailable)||channelDisabled" tone="unknown" title="当前暂不可支付">本次没有扣款，也没有向运营商提交充值。请勿重复创建订单。</StatusNotice></template><view class="page-actions"><button v-if="paymentAvailable" class="primary" :disabled="paying" @click="pay">{{paying?'正在打开微信支付…':'微信支付'}}</button><button v-if="paymentReadState==='READY'&&payment?.state==='UNKNOWN'" class="primary" @click="queryOriginal">查询原支付结果</button><button class="secondary" @click="load">刷新状态</button><button v-if="projection" class="secondary" @click="viewOrder">查看订单</button></view></view></view></template>
<style src="../../styles/shared.css"></style><style scoped>.payment-hero{margin-bottom:26rpx;padding:38rpx;border-radius:38rpx;background:linear-gradient(145deg,#0d4fa8,#2d74cf);color:#fff}.payment-hero.unavailable{background:linear-gradient(145deg,#735019,#a86e18)}.payment-hero text,.payment-hero small{display:block;opacity:.86}.payment-hero strong{display:block;margin:14rpx 0;font-size:56rpx}.kv{display:flex;justify-content:space-between;gap:20rpx;padding:20rpx 0;border-bottom:1rpx solid var(--line)}.kv:last-child{border:0}.kv text:first-child{color:var(--muted)}.kv text:last-child{text-align:right;font-weight:700}.page-actions{display:grid;grid-template-columns:1fr 1fr;gap:16rpx;margin-top:24rpx}.secondary{margin:0}</style>
