<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import AppHeader from '../../components/AppHeader.vue'
import BottomNav from '../../components/BottomNav.vue'
import { api } from '../../api/client'
import type { DirectoryCity, DirectorySummary } from '../../domain/types'
import { directoryCategoryLabel } from '../../domain/directory-display'

const cities=ref<DirectoryCity[]>([]),items=ref<DirectorySummary[]>([]),cityCode=ref(''),category=ref('ALL'),loading=ref(true),error=ref('')
const categories=computed(()=>['ALL',...new Set(items.value.map(item=>item.category))])
const visibleItems=computed(()=>category.value==='ALL'?items.value:items.value.filter(item=>item.category===category.value))
async function load(){loading.value=true;error.value='';try{items.value=await api.getDirectory(cityCode.value||undefined)}catch{items.value=[];error.value='黄页暂时无法读取，请稍后重试。'}finally{loading.value=false}}
async function initialize(){loading.value=true;error.value='';try{cities.value=await api.getDirectoryCities();if(!cities.value.length){items.value=[];error.value='当前没有可用城市，暂时无法读取黄页。';return}cityCode.value=cities.value[0].cityCode}catch{items.value=[];error.value='城市列表暂时无法读取，当前无法加载黄页。';return}finally{loading.value=false}await load()}
const chooseCity=(event:any)=>{cityCode.value=cities.value[Number(event.detail.value)]?.cityCode||'';category.value='ALL';void load()}
const open=(item:DirectorySummary)=>uni.navigateTo({url:`/pages/directory/detail?entryRef=${encodeURIComponent(item.entryRef)}`})
onMounted(initialize)
</script>
<template><view class="page directory-page" data-page-id="UX-P040" data-page-root="directory-list"><AppHeader/><view class="content"><view class="heading">孟加拉黄页</view><text class="desc">按城市和分类查找已发布的生活服务信息</text><picker :disabled="!cities.length" :range="cities" range-key="displayName" @change="chooseCity"><view class="city-filter"><text>当前城市</text><strong>{{cities.find(city=>city.cityCode===cityCode)?.displayName||'请选择城市'}}⌄</strong></view></picker><scroll-view scroll-x class="tabs"><button v-for="tab in categories" :key="tab" :class="{active:category===tab}" @click="category=tab">{{tab==='ALL'?'全部':directoryCategoryLabel(tab)}}</button></scroll-view><view v-if="loading" class="card state">正在读取黄页…</view><view v-else-if="error" class="card state"><text>{{error}}</text><button class="retry" @click="initialize">重新加载</button></view><button v-for="item in visibleItems" :key="item.entryRef" class="card item" @click="open(item)"><text class="entry-symbol">{{directoryCategoryLabel(item.category).slice(0,1)}}</text><view><text class="card-title">{{item.displayName}}</text><text class="copy">{{item.localAddress}}</text><text class="meta">{{directoryCategoryLabel(item.category)}} · {{item.cityName}} · {{item.verifiedAt}} 核验</text></view><text class="arrow">›</text></button><view v-if="!loading&&!error&&!visibleItems.length" class="card state"><text>{{category==='ALL'?'当前城市暂无已发布黄页信息':'当前分类暂无黄页信息'}}</text><button v-if="category!=='ALL'" class="retry" @click="category='ALL'">查看全部分类</button></view></view><BottomNav active="directory"/></view></template>
<style src="../../styles/shared.css"></style><style scoped>.directory-page{padding-bottom:128rpx}.city-filter{margin-top:28rpx;padding:24rpx 28rpx;display:flex;justify-content:space-between;border-radius:24rpx;background:#fff}.city-filter text{color:var(--muted)}.city-filter strong{color:var(--brand)}.tabs{white-space:nowrap;margin:22rpx 0;padding:7rpx;border-radius:22rpx;background:#e8eef7}.tabs button{display:inline-block;margin-right:6rpx;padding:14rpx 28rpx;border-radius:18rpx;color:var(--muted)}.tabs .active{background:#fff;color:var(--brand);font-weight:800}.item{width:100%;display:flex;align-items:center;text-align:left}.item view{flex:1;min-width:0}.entry-symbol{width:76rpx;height:76rpx;margin-right:22rpx;display:flex;align-items:center;justify-content:center;border-radius:22rpx;background:#fff3d8;color:#936211;font-weight:900}.meta{display:block;margin-top:10rpx;color:var(--muted);font-size:22rpx}.arrow{margin-left:16rpx;color:#8793a4;font-size:46rpx}.state{text-align:center}.retry{margin:20rpx auto 0;color:var(--brand);font-weight:800}</style>
