<script setup lang="ts">
import { computed, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import AppHeader from '../../components/AppHeader.vue'
import BottomNav from '../../components/BottomNav.vue'
import { readBuyerSessionToken } from '../../api/buyer-session-token'
import { logoutBuyerSession,requestBuyerAccountClosure } from '../../api/buyer-account-lifecycle-contract'
import { revokeOrderListAccess } from '../../domain/session'
const nickname=ref(''),avatarUrl=ref(''),guestId=ref('')
const sessionActive=ref(false)
const accountActionLoading=ref(false),accountActionStatus=ref('')
const displayName=computed(()=>nickname.value||`${sessionActive.value?'用户':'游客'}${guestId.value}`)
function ensureGuestId(){const stored=uni.getStorageSync('guestDisplayId');if(typeof stored==='string'&&/^\d{6}$/.test(stored)){guestId.value=stored;return}const created=String(Math.floor(100000+Math.random()*900000));uni.setStorageSync('guestDisplayId',created);guestId.value=created}
function loadProfile(){ensureGuestId();sessionActive.value=readBuyerSessionToken()!==null;const stored=uni.getStorageSync('wechatDisplayProfile');if(stored&&typeof stored==='object'){nickname.value=typeof stored.nickname==='string'?stored.nickname.trim():'';avatarUrl.value=typeof stored.avatarUrl==='string'?stored.avatarUrl.trim():''}}
const openOrders=()=>uni.navigateTo({url:'/pages/order/list'}),openRecovery=()=>uni.navigateTo({url:'/pages/order/recovery'})
const openProfileSignIn=()=>{if(!sessionActive.value)uni.navigateTo({url:'/pages/auth/expired'})}
const openUserAgreement=()=>uni.navigateTo({url:'/pages/legal/user-agreement'}),openPrivacyPolicy=()=>uni.navigateTo({url:'/pages/legal/privacy-policy'})
const actionRef=(prefix:string)=>`${prefix}-${Date.now().toString(36)}-${Math.floor(Math.random()*0x100000000).toString(36)}`
const confirmAction=(title:string,content:string)=>new Promise<boolean>(resolve=>uni.showModal({title,content,confirmColor:'#b8453b',success:result=>resolve(result.confirm===true),fail:()=>resolve(false)}))
function becomeGuest(){revokeOrderListAccess(uni);sessionActive.value=false;nickname.value='';avatarUrl.value=''}
async function logout(){
  if(!sessionActive.value||accountActionLoading.value)return
  if(!await confirmAction('退出登录','仅退出当前设备会话，不会注销账号，也不会删除订单。'))return
  accountActionLoading.value=true;accountActionStatus.value=''
  try{const result=await logoutBuyerSession();becomeGuest();accountActionStatus.value=result==='LOGGED_OUT'?'已退出登录。':'退出结果暂时无法确认，本机登录信息已清除。'}catch{accountActionStatus.value='退出登录暂时不可用，请稍后重试。'}finally{accountActionLoading.value=false}
}
async function requestClosure(){
  if(!sessionActive.value||accountActionLoading.value)return
  if(!await confirmAction('申请注销账号','注销申请受理后会立即退出所有设备。进行中的订单、退款或争议处理完成前，账号不会关闭。是否继续？'))return
  accountActionLoading.value=true;accountActionStatus.value=''
  const requestRef=actionRef('CLOSURE')
  try{const result=await requestBuyerAccountClosure(requestRef,'用户在小程序中主动申请注销账号',actionRef('IDEMPOTENCY'));becomeGuest();accountActionStatus.value=result.blockerCount>0?`注销申请已受理，仍有 ${result.blockerCount} 项事项待完成。`:'注销申请已受理，正在等待个人信息清理完成。'}catch(cause){if(readBuyerSessionToken()===null)becomeGuest();accountActionStatus.value=cause instanceof Error&&cause.message==='BUYER_CLOSURE_CONFLICT'?'注销申请与当前账号状态冲突，请通过微信客服核验。':'注销申请暂时不可用，请稍后重试。'}finally{accountActionLoading.value=false}
}
onShow(loadProfile)
</script>
<template><view class="page profile-page" data-page-id="UX-P024" data-page-root="profile"><AppHeader/><view class="content"><view class="heading" role="heading" aria-level="1">我的</view><view class="profile-card" :class="{'profile-card-action':!sessionActive}" :role="sessionActive?undefined:'button'" @click="openProfileSignIn"><image v-if="avatarUrl" class="avatar" :src="avatarUrl" mode="aspectFill"/><view v-else class="avatar fallback" aria-label="默认头像">人</view><view class="profile-copy"><text class="profile-name">{{displayName}}</text><template v-if="!sessionActive"><text>点击登录或注册</text><small>登录后可查看订单并使用充值服务</small></template></view><text v-if="!sessionActive" class="profile-chevron">›</text></view><view class="service-card"><text class="section-title">常用服务</text><button class="service-row" @click="openOrders"><text class="service-icon blue">▤</text><view><text>我的订单</text><small>查看充值、支付与退款进度</small></view><text class="chevron">›</text></button><button class="service-row" @click="openRecovery"><text class="service-icon gold">↻</text><view><text>找回历史订单</text><small>订单没有显示时使用</small></view><text class="chevron">›</text></button></view><view class="service-card"><text class="section-title">协议与账号</text><button class="service-row" @click="openUserAgreement"><text class="service-icon blue">文</text><view><text>用户协议</text><small>查看当前用户协议</small></view><text class="chevron">›</text></button><button class="service-row" @click="openPrivacyPolicy"><text class="service-icon green">隐</text><view><text>隐私政策</text><small>查看个人信息处理规则</small></view><text class="chevron">›</text></button><button class="service-row" :disabled="!sessionActive||accountActionLoading" @click="logout"><text class="service-icon gold">退</text><view><text>退出登录</text><small>{{sessionActive?'仅退出当前会话，不会注销账号':'当前未登录，无需退出'}}</small></view><text class="status-pill">{{sessionActive?'可操作':'未登录'}}</text></button><button class="service-row" :disabled="!sessionActive||accountActionLoading" @click="requestClosure"><text class="service-icon red">销</text><view><text>注销账号</text><small>{{sessionActive?'提交注销申请，受理后立即退出所有设备':'请先完成登录后再申请注销'}}</small></view><text class="status-pill">{{sessionActive?'申请注销':'需登录'}}</text></button><text v-if="accountActionStatus" class="account-status">{{accountActionStatus}}</text></view><button class="support-card" open-type="contact"><text class="service-icon green">☏</text><view><text>微信客服</text><small>订单、支付、充值、退款或隐私问题</small></view><text class="chevron">›</text></button></view><BottomNav active="profile"/></view></template>
<style src="../../styles/shared.css"></style><style scoped>.profile-page{padding-bottom:128rpx}.profile-card{margin-top:24rpx;padding:34rpx 30rpx;display:flex;align-items:center;border-radius:36rpx;background:linear-gradient(135deg,#195bb8,#3475cb);color:#fff;box-shadow:0 14rpx 34rpx rgba(25,91,184,.18)}.avatar{width:112rpx;height:112rpx;flex:none;border-radius:50%;background:rgba(255,255,255,.18)}.fallback{display:flex;align-items:center;justify-content:center;color:#fff;font-size:38rpx;font-weight:800}.profile-copy{min-width:0;margin-left:24rpx}.profile-copy text,.profile-copy small{display:block}.profile-name{font-size:36rpx;font-weight:800}.profile-copy>text:not(.profile-name){margin-top:7rpx;color:#dceaff;font-size:22rpx}.profile-copy small{margin-top:7rpx;color:#bfd5f5;font-size:19rpx;line-height:1.4}.service-card,.support-card{width:100%;margin-top:24rpx;padding:30rpx;border-radius:32rpx;background:#fff;text-align:left}.section-title{display:block;font-size:30rpx;font-weight:800}.service-row,.support-card{display:flex;align-items:center}.service-row{width:100%;min-height:118rpx;border-bottom:1rpx solid var(--line)}.service-row:last-child{border-bottom:0}.service-row view,.support-card view{flex:1}.service-row view text,.service-row small,.support-card view text,.support-card small{display:block}.service-row view text,.support-card view text{font-weight:800}.service-row small,.support-card small{margin-top:6rpx;color:var(--muted);font-size:21rpx}.service-icon{width:66rpx;height:66rpx;margin-right:22rpx;display:flex;align-items:center;justify-content:center;border-radius:20rpx;font-size:30rpx}.blue{background:#eaf2ff;color:#195bb8}.gold{background:#fff3d8;color:#936211}.green{background:#eaf6f2;color:#19865d}.red{background:#fff0ef;color:#b8453b}.status-pill{margin-left:12rpx;padding:8rpx 13rpx;border-radius:999rpx;background:#f1f3f6;color:#6f7b8a;font-size:19rpx;white-space:nowrap}.account-status{display:block;margin-top:22rpx;padding:18rpx;border-radius:18rpx;background:#f3f6fa;color:var(--muted);font-size:22rpx;line-height:1.55}.chevron{color:#8793a4;font-size:44rpx}</style>
