<script setup lang="ts">
import { computed, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import AppHeader from '../../components/AppHeader.vue'
import BottomNav from '../../components/BottomNav.vue'
const nickname=ref(''),avatarUrl=ref(''),guestId=ref('')
const displayName=computed(()=>nickname.value||`游客${guestId.value}`)
function ensureGuestId(){const stored=uni.getStorageSync('guestDisplayId');if(typeof stored==='string'&&/^\d{6}$/.test(stored)){guestId.value=stored;return}const created=String(Math.floor(100000+Math.random()*900000));uni.setStorageSync('guestDisplayId',created);guestId.value=created}
function loadProfile(){ensureGuestId();const stored=uni.getStorageSync('wechatDisplayProfile');if(stored&&typeof stored==='object'){nickname.value=typeof stored.nickname==='string'?stored.nickname.trim():'';avatarUrl.value=typeof stored.avatarUrl==='string'?stored.avatarUrl.trim():''}}
const openOrders=()=>uni.navigateTo({url:'/pages/order/list'}),openRecovery=()=>uni.navigateTo({url:'/pages/order/recovery'})
onShow(loadProfile)
</script>
<template><view class="page profile-page" data-page-id="UX-P024" data-page-root="profile"><AppHeader/><view class="content"><view class="heading" role="heading" aria-level="1">我的</view><view class="profile-card"><image v-if="avatarUrl" class="avatar" :src="avatarUrl" mode="aspectFill"/><view v-else class="avatar fallback" aria-label="默认头像">人</view><view class="profile-copy"><text class="profile-name">{{displayName}}</text><text>{{avatarUrl?'已使用微信头像':'当前使用默认头像'}}</text><small>头像与昵称授权不影响登录、下单和订单查询</small></view></view><view class="service-card"><text class="section-title">常用服务</text><button class="service-row" @click="openOrders"><text class="service-icon blue">▤</text><view><text>我的订单</text><small>查看充值、支付与退款进度</small></view><text class="chevron">›</text></button><button class="service-row" @click="openRecovery"><text class="service-icon gold">↻</text><view><text>找回历史订单</text><small>订单没有显示时使用</small></view><text class="chevron">›</text></button></view><button class="support-card" open-type="contact"><text class="service-icon green">☏</text><view><text>微信客服</text><small>订单、支付、充值或退款问题</small></view><text class="chevron">›</text></button></view><BottomNav active="profile"/></view></template>
<style src="../../styles/shared.css"></style><style scoped>.profile-page{padding-bottom:128rpx}.profile-card{margin-top:24rpx;padding:34rpx 30rpx;display:flex;align-items:center;border-radius:36rpx;background:linear-gradient(135deg,#195bb8,#3475cb);color:#fff;box-shadow:0 14rpx 34rpx rgba(25,91,184,.18)}.avatar{width:112rpx;height:112rpx;flex:none;border-radius:50%;background:rgba(255,255,255,.18)}.fallback{display:flex;align-items:center;justify-content:center;color:#fff;font-size:38rpx;font-weight:800}.profile-copy{min-width:0;margin-left:24rpx}.profile-copy text,.profile-copy small{display:block}.profile-name{font-size:36rpx;font-weight:800}.profile-copy>text:not(.profile-name){margin-top:7rpx;color:#dceaff;font-size:22rpx}.profile-copy small{margin-top:7rpx;color:#bfd5f5;font-size:19rpx;line-height:1.4}.service-card,.support-card{width:100%;margin-top:24rpx;padding:30rpx;border-radius:32rpx;background:#fff;text-align:left}.section-title{display:block;font-size:30rpx;font-weight:800}.service-row,.support-card{display:flex;align-items:center}.service-row{width:100%;min-height:118rpx;border-bottom:1rpx solid var(--line)}.service-row:last-child{border-bottom:0}.service-row view,.support-card view{flex:1}.service-row view text,.service-row small,.support-card view text,.support-card small{display:block}.service-row view text,.support-card view text{font-weight:800}.service-row small,.support-card small{margin-top:6rpx;color:var(--muted);font-size:21rpx}.service-icon{width:66rpx;height:66rpx;margin-right:22rpx;display:flex;align-items:center;justify-content:center;border-radius:20rpx;font-size:30rpx}.blue{background:#eaf2ff;color:#195bb8}.gold{background:#fff3d8;color:#936211}.green{background:#eaf6f2;color:#19865d}.chevron{color:#8793a4;font-size:44rpx}</style>
