package com.huarenzaimeng.api.topup;

import com.huarenzaimeng.api.BusinessEventStore;
import com.huarenzaimeng.core.BusinessEventLinker;
import com.huarenzaimeng.api.recovery.RecoveryTaskStore;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Profile;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;
import java.sql.Timestamp;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.Instant;
import java.util.UUID;

@Repository @Profile("release-mysql")
class JdbcTopupStore implements TopupCoordinator.Store {
    private final JdbcTemplate jdbc;private final BusinessEventStore events;private final RecoveryTaskStore recovery;private final JdbcProviderExposureStore exposures;
    JdbcTopupStore(JdbcTemplate jdbc){this(jdbc,null,null,null);}
    JdbcTopupStore(JdbcTemplate jdbc,BusinessEventStore events){this(jdbc,events,null,null);}
    JdbcTopupStore(JdbcTemplate jdbc,BusinessEventStore events,RecoveryTaskStore recovery){this(jdbc,events,recovery,null);}
    @Autowired JdbcTopupStore(JdbcTemplate jdbc,BusinessEventStore events,RecoveryTaskStore recovery,JdbcProviderExposureStore exposures){this.jdbc=jdbc;this.events=events;this.recovery=recovery;this.exposures=exposures;}
    @Transactional public TopupCoordinator.Begin beginAndReserve(TopupProviderPort.Command c,TopupEligibilityPort.Snapshot s,int budget){
        validateScope(s);
        Stored existing=stored(c.merchantOrderRef());
        if(existing!=null)return same(existing,c,s)?TopupCoordinator.Begin.REPLAY:TopupCoordinator.Begin.CONFLICT;
        if(exposures==null)throw new TopupCoordinator.Conflict("TOPUP_EXPOSURE_STORE_UNAVAILABLE");
        try{jdbc.update("INSERT INTO hz_topup_coordination (merchant_order_ref,request_ref,request_digest,buyer_subject_ref,provider_sku,recipient,entitlement_digest,provider_code,submit_latched,unknown_queries_remaining,state_code,reserved_minor,reserve_currency,aggregate_version,updated_at,scope_provider_code,scope_channel_ref,scope_operator_code,supplier_cost) VALUES (?,?,?,?,?,?,?,'WINLA',1,?,'RESERVED',?,?,1,CURRENT_TIMESTAMP(3),'WINLA',?,?,?)",c.merchantOrderRef(),c.requestRef(),c.requestDigest(),s.buyerSubjectRef(),c.providerSku(),c.recipient(),s.entitlementDigest(),budget,c.faceValueMinor(),c.targetCurrency(),s.channelRef(),s.operatorCode(),s.supplierCost());}
        catch(DuplicateKeyException duplicate){Stored current=stored(c.merchantOrderRef());return current!=null&&same(current,c,s)?TopupCoordinator.Begin.REPLAY:TopupCoordinator.Begin.CONFLICT;}
        exposures.reserve(c.merchantOrderRef(),"WINLA",s.channelRef(),s.operatorCode(),c.targetCurrency(),c.faceValueMinor());
        reserveBalance(c);
        jdbc.update("INSERT INTO hz_provider_balance_reservation (reservation_ref,merchant_order_ref,provider_code,amount_minor,currency,reservation_state,created_at,updated_at) VALUES (?,?,'WINLA',?,?,'RESERVED',CURRENT_TIMESTAMP(3),CURRENT_TIMESTAMP(3))","RES-"+UUID.randomUUID(),c.merchantOrderRef(),c.faceValueMinor(),c.targetCurrency());
        jdbc.update("INSERT INTO hz_provider_balance_ledger (entry_ref,merchant_order_ref,entry_type,amount_minor,currency,occurred_at) VALUES (?,?,'RESERVE',?,?,CURRENT_TIMESTAMP(3))","LEDGER-"+UUID.randomUUID(),c.merchantOrderRef(),c.faceValueMinor(),c.targetCurrency());
        append(c.merchantOrderRef(),BusinessEventLinker.Type.TOPUP_SUBMITTED,"TOPUP-SUBMIT-"+c.requestRef(),c.requestDigest(),Instant.now());return TopupCoordinator.Begin.CREATED;
    }
    public TopupCoordinator.View require(String ref){return jdbc.query("SELECT merchant_order_ref,request_ref,request_digest,buyer_subject_ref,provider_sku,recipient,entitlement_digest,provider_ref,state_code,reserved_minor,reserve_currency,unknown_queries_remaining,evidence_ref,aggregate_version,updated_at FROM hz_topup_coordination WHERE merchant_order_ref=?",(rs,n)->view(rs),ref).stream().findFirst().orElseThrow(()->new TopupCoordinator.Conflict("TOPUP_NOT_FOUND"));}
    @Transactional public void submissionResult(String ref,String provider,TopupCoordinator.State state,String evidence){
        boolean changed=advance(ref,provider,state,evidence);
        if(changed&&state==TopupCoordinator.State.DELIVERED)completeDelivery(ref);
        if(changed&&state==TopupCoordinator.State.UNKNOWN)scheduleTopup(ref);
    }
    @Transactional public void submissionRejectedAndRelease(String ref,String evidence){if(advance(ref,null,TopupCoordinator.State.REJECTED,evidence))release(ref,"RELEASE_REJECTED");}
    public void consumeUnknownQuery(String ref){if(jdbc.update("UPDATE hz_topup_coordination SET unknown_queries_remaining=unknown_queries_remaining-1,aggregate_version=aggregate_version+1,updated_at=CURRENT_TIMESTAMP(3) WHERE merchant_order_ref=? AND state_code IN ('PROCESSING','UNKNOWN') AND unknown_queries_remaining>0",ref)!=1)throw new TopupCoordinator.Conflict("TOPUP_QUERY_BUDGET_EXHAUSTED");}
    @Transactional public void observation(String ref,TopupCoordinator.State state,String evidence){
        boolean changed=advance(ref,null,state,evidence);
        if(changed&&state==TopupCoordinator.State.DELIVERED)completeDelivery(ref);
        if(changed&&state==TopupCoordinator.State.UNKNOWN)scheduleTopup(ref);
    }
    @Transactional public TopupCoordinator.CallbackDisposition callback(TopupProviderPort.VerifiedCallback c,TopupCoordinator.State state){
        try{jdbc.update("INSERT INTO hz_topup_callback (callback_id,merchant_order_ref,provider_ref,callback_digest,amount_minor,currency,provider_sku,recipient,state_code,occurred_at,observed_at) VALUES (?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP(3))",c.callbackId(),c.merchantOrderRef(),c.providerRef(),c.callbackDigest(),c.amountMinor(),c.currency(),c.providerSku(),c.recipient(),state.name(),Timestamp.from(c.occurredAt()));}
        catch(DuplicateKeyException duplicate){String digest=jdbc.queryForObject("SELECT callback_digest FROM hz_topup_callback WHERE callback_id=?",String.class,c.callbackId());if(!c.callbackDigest().equals(digest))throw new TopupCoordinator.Conflict("TOPUP_CALLBACK_ID_CONFLICT");return TopupCoordinator.CallbackDisposition.REPLAY;}
        boolean changed=advance(c.merchantOrderRef(),c.providerRef(),state,c.evidenceRef());if(changed&&state==TopupCoordinator.State.DELIVERED){release(c.merchantOrderRef(),"CONSUMED");append(c.merchantOrderRef(),BusinessEventLinker.Type.TOPUP_DELIVERED,"TOPUP-CALLBACK-"+c.callbackId(),c.callbackDigest(),c.occurredAt());}return TopupCoordinator.CallbackDisposition.ACCEPTED;
    }
    @Transactional public void reconciliationRequired(String ref,String evidence){boolean changed=advance(ref,null,TopupCoordinator.State.RECONCILIATION_REQUIRED,evidence);if(changed||require(ref).state()==TopupCoordinator.State.RECONCILIATION_REQUIRED){jdbc.update("INSERT INTO hz_provider_reconciliation_task (task_ref,merchant_order_ref,reason_code,state_code,created_at,updated_at) VALUES (?, ?,?,'OPEN',CURRENT_TIMESTAMP(3),CURRENT_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE reason_code=VALUES(reason_code),updated_at=VALUES(updated_at)","RECON-"+ref,ref,evidence);if(changed)append(ref,BusinessEventLinker.Type.RECONCILIATION_OPENED,"TOPUP-RECON-"+ref,"RECON-"+ref,Instant.now());}}
    public long reservedTotal(String currency){BigDecimal value=jdbc.queryForObject("SELECT active_reserved_minor FROM hz_provider_balance_position WHERE provider_code='WINLA' AND currency=?",BigDecimal.class,currency);return unsigned(value,"TOPUP_BALANCE_COUNTER_INVALID");}
    public void recordBalanceObservation(String provider,String currency,long amount,Instant observedAt,String evidence){if(amount<0)throw new TopupCoordinator.Conflict("TOPUP_BALANCE_INVALID");jdbc.update("INSERT INTO hz_provider_balance_position(provider_code,currency,confirmed_balance_minor,safety_buffer_minor,active_reserved_minor,observed_at,expires_at,evidence_ref,updated_at) VALUES (?,?,?,0,0,?,DATE_ADD(?,INTERVAL 15 MINUTE),?,CURRENT_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE confirmed_balance_minor=VALUES(confirmed_balance_minor),observed_at=VALUES(observed_at),expires_at=VALUES(expires_at),evidence_ref=VALUES(evidence_ref),updated_at=VALUES(updated_at)",provider,currency,amount,Timestamp.from(observedAt),Timestamp.from(observedAt),evidence);}
    private boolean advance(String ref,String provider,TopupCoordinator.State next,String evidence){String sources=switch(next){case RESERVED->"'RESERVED'";case SUBMITTED->"'RESERVED','SUBMITTED'";case PROCESSING->"'RESERVED','SUBMITTED','PROCESSING','UNKNOWN'";case UNKNOWN->"'RESERVED','SUBMITTED','PROCESSING','UNKNOWN'";case DELIVERED->"'SUBMITTED','PROCESSING','UNKNOWN'";case REJECTED->"'RESERVED','SUBMITTED','PROCESSING','UNKNOWN'";case RECONCILIATION_REQUIRED->"'SUBMITTED','PROCESSING','UNKNOWN'";};return jdbc.update("UPDATE hz_topup_coordination SET provider_ref=COALESCE(?,provider_ref),state_code=?,evidence_ref=?,aggregate_version=aggregate_version+1,updated_at=CURRENT_TIMESTAMP(3) WHERE merchant_order_ref=? AND state_code IN ("+sources+")",provider,next.name(),evidence,ref)==1;}
    private void release(String ref,String type){int changed=jdbc.update("UPDATE hz_provider_balance_reservation SET reservation_state=?,aggregate_version=aggregate_version+1,updated_at=CURRENT_TIMESTAMP(3) WHERE merchant_order_ref=? AND reservation_state='RESERVED'",type,ref);if(changed==1){TopupCoordinator.View v=require(ref);releaseBalance(v);jdbc.update("INSERT INTO hz_provider_balance_ledger (entry_ref,merchant_order_ref,entry_type,amount_minor,currency,occurred_at) VALUES (?,?,?,?,?,CURRENT_TIMESTAMP(3))","LEDGER-"+UUID.randomUUID(),ref,type,-v.reservedMinor(),v.reserveCurrency());if(exposures!=null){if("CONSUMED".equals(type))exposures.settle(ref);else exposures.release(ref);}}}
    private void completeDelivery(String ref){TopupCoordinator.View current=require(ref);release(ref,"CONSUMED");append(ref,BusinessEventLinker.Type.TOPUP_DELIVERED,"TOPUP-DELIVERED-"+current.requestDigest().substring(0,24),current.requestDigest(),Instant.now());}
    private void scheduleTopup(String ref){if(recovery!=null){TopupCoordinator.View current=require(ref);recovery.schedule(ref,"WINLA_TOPUP_QUERY",current.version(),current.unknownQueriesRemaining(),Instant.now().plusSeconds(300),Instant.now());}}
    private void append(String orderRef,BusinessEventLinker.Type type,String eventRef,String digest,Instant at){if(events!=null)events.append(new BusinessEventStore.EventDraft(orderRef,type,eventRef,digest,at));}
    private static TopupCoordinator.View view(java.sql.ResultSet rs)throws java.sql.SQLException{return new TopupCoordinator.View(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),TopupCoordinator.State.valueOf(rs.getString(9)),rs.getLong(10),rs.getString(11),rs.getInt(12),rs.getString(13),rs.getLong(14),rs.getTimestamp(15).toInstant());}
    private Stored stored(String ref){return jdbc.query("SELECT request_ref,request_digest,buyer_subject_ref,provider_sku,recipient,entitlement_digest,reserved_minor,reserve_currency,scope_provider_code,scope_channel_ref,scope_operator_code,supplier_cost FROM hz_topup_coordination WHERE merchant_order_ref=? FOR UPDATE",(rs,n)->new Stored(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getLong(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getBigDecimal(12)),ref).stream().findFirst().orElse(null);}
    private static boolean same(Stored old,TopupProviderPort.Command c,TopupEligibilityPort.Snapshot s){return old.requestDigest().equals(c.requestDigest())&&old.requestRef().equals(c.requestRef())&&old.entitlementDigest().equals(s.entitlementDigest())&&old.buyerSubjectRef().equals(s.buyerSubjectRef())&&old.providerSku().equals(c.providerSku())&&old.recipient().equals(c.recipient())&&old.reservedMinor()==c.faceValueMinor()&&old.reserveCurrency().equals(c.targetCurrency())&&"WINLA".equals(old.provider())&&old.channel().equals(s.channelRef())&&old.operator().equals(s.operatorCode())&&old.supplierCost()!=null&&old.supplierCost().compareTo(s.supplierCost())==0;}
    private void reserveBalance(TopupProviderPort.Command c){Balance balance=jdbc.query("SELECT confirmed_balance_minor,safety_buffer_minor,active_reserved_minor,expires_at FROM hz_provider_balance_position WHERE provider_code='WINLA' AND currency=? FOR UPDATE",(rs,n)->new Balance(unsignedBig(rs.getBigDecimal(1),"TOPUP_BALANCE_INVALID"),unsignedBig(rs.getBigDecimal(2),"TOPUP_BALANCE_INVALID"),unsignedBig(rs.getBigDecimal(3),"TOPUP_BALANCE_COUNTER_INVALID"),rs.getTimestamp(4).toInstant()),c.targetCurrency()).stream().findFirst().orElseThrow(()->new TopupCoordinator.Conflict("TOPUP_BALANCE_UNKNOWN"));if(Instant.now().isAfter(balance.expiresAt()))throw new TopupCoordinator.Conflict("TOPUP_BALANCE_STALE");BigInteger available=balance.confirmed().subtract(balance.active()).subtract(balance.safety());if(available.signum()<0||available.compareTo(BigInteger.valueOf(c.faceValueMinor()))<0)throw new TopupCoordinator.Conflict("TOPUP_BALANCE_INSUFFICIENT");long next=exactLong(balance.active().add(BigInteger.valueOf(c.faceValueMinor())),"TOPUP_BALANCE_OVERFLOW");jdbc.update("UPDATE hz_provider_balance_position SET active_reserved_minor=?,updated_at=CURRENT_TIMESTAMP(3) WHERE provider_code='WINLA' AND currency=?",next,c.targetCurrency());}
    private void releaseBalance(TopupCoordinator.View v){BigDecimal active=jdbc.queryForObject("SELECT active_reserved_minor FROM hz_provider_balance_position WHERE provider_code='WINLA' AND currency=? FOR UPDATE",BigDecimal.class,v.reserveCurrency());long next;try{next=Math.subtractExact(unsigned(active,"TOPUP_BALANCE_COUNTER_INVALID"),v.reservedMinor());if(next<0)throw new ArithmeticException("negative");}catch(ArithmeticException invalid){throw new TopupCoordinator.Conflict("TOPUP_BALANCE_COUNTER_INVALID");}jdbc.update("UPDATE hz_provider_balance_position SET active_reserved_minor=?,updated_at=CURRENT_TIMESTAMP(3) WHERE provider_code='WINLA' AND currency=?",next,v.reserveCurrency());}
    private static void validateScope(TopupEligibilityPort.Snapshot s){if(s.channelRef()==null||s.channelRef().isBlank()||"UNSCOPED".equals(s.channelRef())||s.operatorCode()==null||s.operatorCode().isBlank()||"UNSCOPED".equals(s.operatorCode())||s.supplierCost()==null||s.supplierCost().signum()<0)throw new TopupCoordinator.Conflict("TOPUP_SCOPE_INCOMPLETE");}
    private static long unsigned(BigDecimal value,String code){return exactLong(unsignedBig(value,code),code);}
    private static BigInteger unsignedBig(BigDecimal value,String code){try{BigInteger result=value.toBigIntegerExact();if(result.signum()<0)throw new ArithmeticException("negative");return result;}catch(ArithmeticException|NullPointerException invalid){throw new TopupCoordinator.Conflict(code);}}
    private static long exactLong(BigInteger value,String code){try{return value.longValueExact();}catch(ArithmeticException invalid){throw new TopupCoordinator.Conflict(code);}}
    private record Stored(String requestRef,String requestDigest,String buyerSubjectRef,String providerSku,String recipient,String entitlementDigest,long reservedMinor,String reserveCurrency,String provider,String channel,String operator,BigDecimal supplierCost){}
    private record Balance(BigInteger confirmed,BigInteger safety,BigInteger active,Instant expiresAt){}
    static boolean allowed(TopupCoordinator.State from,TopupCoordinator.State to){if(from==to)return true;return switch(from){case RESERVED->java.util.Set.of(TopupCoordinator.State.SUBMITTED,TopupCoordinator.State.PROCESSING,TopupCoordinator.State.UNKNOWN,TopupCoordinator.State.REJECTED).contains(to);case SUBMITTED,PROCESSING,UNKNOWN->java.util.Set.of(TopupCoordinator.State.PROCESSING,TopupCoordinator.State.UNKNOWN,TopupCoordinator.State.DELIVERED,TopupCoordinator.State.REJECTED,TopupCoordinator.State.RECONCILIATION_REQUIRED).contains(to);case DELIVERED,REJECTED,RECONCILIATION_REQUIRED->false;};}
}
