<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { loadA140Detail, type A140Detail } from '../api/admin-a140-detail'
const props=defineProps<{orderRef:string}>();defineEmits<{close:[]}>()
const detail=ref<A140Detail|null>(null),loading=ref(true),error=ref('')
const money=(value:number|null,currency:string|null)=>value===null||!currency?'无法确认':`${currency} ${(value/100).toFixed(2)}`
const state=(value:string)=>({UNKNOWN:'状态尚未确认',CREATED:'已创建',PAYMENT_PENDING:'等待付款',PAID:'支付成功',PROCESSING:'处理中',PREPAY_CREATED:'等待支付',CLOSED:'已关闭',REJECTED:'处理失败',TOPUP_PENDING:'等待充值',TOPUP_PROCESSING:'充值处理中',TOPUP_SUCCEEDED:'充值成功',TOPUP_FAILED:'充值失败',REFUND_PROCESSING:'退款处理中',REFUNDED:'已退款'}[value]??'状态待确认')
const event=(value:string)=>({ORDER_CREATED:'订单已创建',PAYMENT_CREATED:'支付已创建',PAYMENT_PAID:'支付已完成',TOPUP_SUBMITTED:'充值已提交',TOPUP_SUCCEEDED:'充值已完成',TOPUP_FAILED:'充值失败',REFUND_CREATED:'退款已申请',REFUND_SUCCEEDED:'退款已完成'}[value]??'订单处理记录')
const time=(value:string|null)=>value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'暂无记录'
const productType=(value:string)=>({BALANCE:'余额',DATA:'流量',BUNDLE:'套餐'}[value]??'权益类型待确认')
async function read(){loading.value=true;error.value='';detail.value=null;try{detail.value=await loadA140Detail(props.orderRef)}catch(e){error.value=e instanceof Error?e.message:'订单详情暂不可用，请稍后重试'}finally{loading.value=false}}
watch(()=>props.orderRef,read);onMounted(read)
</script>
<template><section class="card p021-admin-detail" data-page-id="UX-A140-DETAIL" data-read-state="FORMAL_READ_ONLY"><div class="card-head"><div><p class="eyebrow">订单详情</p><h2>{{orderRef}}</h2></div><button class="secondary" @click="$emit('close')">返回列表</button></div>
 <div v-if="loading" class="empty-panel" role="status">正在读取订单详情</div><div v-else-if="error" class="empty-panel" role="alert"><strong>{{error}}</strong><div class="form-actions"><button class="secondary" @click="read">重新读取</button></div></div>
 <template v-else-if="detail"><section class="admin-detail-section"><h3>订单信息</h3><dl class="admin-order-detail-grid"><div><dt>订单号</dt><dd>{{detail.order.orderRef}}</dd></div><div><dt>状态</dt><dd>{{state(detail.order.state)}}</dd></div><div><dt>订单金额</dt><dd>{{money(detail.order.amountMinor,detail.order.currency)}}</dd></div><div><dt>充值号码</dt><dd>{{detail.order.phoneMasked}}</dd></div><div><dt>运营商</dt><dd>{{detail.order.operatorCode}}</dd></div><div><dt>商品编号</dt><dd>{{detail.order.productRef}}</dd></div><div><dt>创建时间</dt><dd>{{time(detail.order.createdAt)}}</dd></div></dl></section>
  <section class="admin-detail-section"><h3>商品权益</h3><div v-if="!detail.order.entitlement" class="empty-panel">权益内容暂时无法确认</div><dl v-else class="admin-order-detail-grid"><div><dt>商品名称</dt><dd>{{detail.order.entitlement.displayName}}</dd></div><div><dt>权益类型</dt><dd>{{productType(detail.order.entitlement.productType)}}</dd></div><div><dt>权益说明</dt><dd>{{detail.order.entitlement.benefitText}}</dd></div><div v-if="detail.order.entitlement.denominationBdt!==null"><dt>余额面值</dt><dd>{{detail.order.entitlement.denominationBdt}} BDT</dd></div><div v-if="detail.order.entitlement.dataAllowanceMb!==null"><dt>流量</dt><dd>{{detail.order.entitlement.dataAllowanceMb}} MB</dd></div><div v-if="detail.order.entitlement.voiceMinutes!==null"><dt>通话</dt><dd>{{detail.order.entitlement.voiceMinutes}} 分钟</dd></div><div v-if="detail.order.entitlement.smsCount!==null"><dt>短信</dt><dd>{{detail.order.entitlement.smsCount}} 条</dd></div><div v-if="detail.order.entitlement.validityText"><dt>有效期</dt><dd>{{detail.order.entitlement.validityText}}</dd></div></dl></section>
  <section class="admin-detail-section"><h3>支付与充值</h3><div class="admin-order-detail-grid"><div><dt>支付状态</dt><dd>{{state(detail.payment.state)}}</dd><small>{{money(detail.payment.amountMinor,detail.payment.currency)}} · 已退款 {{money(detail.payment.refundedMinor,detail.payment.currency)}}</small></div><div><dt>充值状态</dt><dd>{{state(detail.topup.state)}}</dd><small>更新时间：{{time(detail.topup.updatedAt)}}</small></div></div></section>
  <section class="admin-detail-section"><h3>退款记录</h3><div v-if="!detail.refunds.length" class="empty-panel">没有退款记录</div><div v-else class="history-list"><article v-for="item in detail.refunds" :key="item.refundRef"><strong>{{item.refundRef}} · {{state(item.state)}}</strong><p>{{money(item.amountMinor,item.currency)}}</p><small>{{time(item.createdAt)}}</small></article></div></section>
  <section class="admin-detail-section"><h3>处理轨迹</h3><div v-if="!detail.timeline.length" class="empty-panel">暂无处理轨迹</div><div v-else class="history-list"><article v-for="item in detail.timeline" :key="item.eventRef"><strong>{{event(item.eventType)}}</strong><p>{{time(item.occurredAt)}}</p></article></div></section>
  <section class="admin-detail-section reference-grid"><div><h3>交易差异</h3><p>{{detail.reconciliationRefs.length?detail.reconciliationRefs.join('、'):'暂无关联记录'}}</p></div><div><h3>客服案件</h3><p>{{detail.customerCaseRefs.length?detail.customerCaseRefs.join('、'):'暂无关联记录'}}</p></div></section>
  <div class="safe-note warning"><strong>交易安全</strong><p>当前页面仅查询订单、支付、充值和退款事实，不会发起支付、重复充值、退款、调账或修改交易状态。</p></div></template>
</section></template>
