ALTER TABLE hz_order
  ADD COLUMN environment VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'LOCAL_SYNTHETIC',
  ADD COLUMN evidence_level VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'L1',
  ADD COLUMN authority_state VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'NON_PRODUCTION';
