CREATE TABLE hz_release_quote_snapshot (
    quote_ref VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    project_subject_ref VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_ref VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    idempotency_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    phone_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    phone_masked VARCHAR(32) NOT NULL,
    operator_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    platform_product_ref VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    product_aggregate_version BIGINT UNSIGNED NOT NULL,
    entitlement_snapshot JSON NOT NULL,
    price_version_ref VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    price_aggregate_version BIGINT UNSIGNED NOT NULL,
    price_snapshot JSON NOT NULL,
    final_amount_minor BIGINT UNSIGNED NOT NULL,
    currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    supported_operator_set_version BIGINT UNSIGNED NOT NULL,
    catalog_version BIGINT UNSIGNED NOT NULL,
    valid_until DATETIME(3) NOT NULL,
    snapshot_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (quote_ref),
    UNIQUE KEY uk_hz_release_quote_request (project_subject_ref,request_ref),
    UNIQUE KEY uk_hz_release_quote_idempotency (project_subject_ref,idempotency_key),
    KEY idx_hz_release_quote_valid (project_subject_ref,valid_until),
    CONSTRAINT fk_hz_release_quote_base FOREIGN KEY (quote_ref) REFERENCES hz_quote (quote_ref)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE hz_release_order_snapshot (
    order_ref VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    quote_ref VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    project_subject_ref VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_ref VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    idempotency_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    quote_snapshot JSON NOT NULL,
    entitlement_snapshot JSON NOT NULL,
    price_snapshot JSON NOT NULL,
    price_version_ref VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    final_amount_minor BIGINT UNSIGNED NOT NULL,
    currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    price_snapshot_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    quote_snapshot_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    snapshot_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (order_ref),
    UNIQUE KEY uk_hz_release_order_quote (quote_ref),
    UNIQUE KEY uk_hz_release_order_request (project_subject_ref,request_ref),
    UNIQUE KEY uk_hz_release_order_idempotency (project_subject_ref,idempotency_key),
    CONSTRAINT fk_hz_release_order_base FOREIGN KEY (order_ref) REFERENCES hz_order (order_ref),
    CONSTRAINT fk_hz_release_order_quote FOREIGN KEY (quote_ref) REFERENCES hz_release_quote_snapshot (quote_ref)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
