CREATE TABLE hz_provider_exchange_attempt (
    exchange_ref VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    provider_code VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    operation_code VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    merchant_order_ref VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    provider_request_ref VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    local_amount_minor BIGINT UNSIGNED NOT NULL,
    local_currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    provider_amount_raw VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    provider_currency_raw VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    provider_sku VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    recipient_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    canonical_request_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    raw_response_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    provider_ref VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
    contract_version VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    observed_at DATETIME(3) NOT NULL,
    normalized_amount_minor BIGINT UNSIGNED DEFAULT NULL,
    normalized_currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
    normalization_status VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (exchange_ref),
    UNIQUE KEY uk_hz_provider_exchange_request (provider_code,provider_request_ref),
    KEY idx_hz_provider_exchange_order (merchant_order_ref,operation_code,observed_at),
    KEY idx_hz_provider_exchange_provider_ref (provider_code,provider_ref)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
